// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public final class AgentProto extends com.google.protobuf.GeneratedFile {
  private AgentProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AgentProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ReportInterval_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ReportInterval_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_SessionDeadline_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_SessionDeadline_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_Hello_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_Hello_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_PlayerCount_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_PlayerCount_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_CloudRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_CloudRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_CloudResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_CloudResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ConnectRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ConnectRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ConnectResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ConnectResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_RetireRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_RetireRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_RetireResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_RetireResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_UnretireRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_UnretireRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_UnretireResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_UnretireResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_StatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_StatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ResourceUsage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ResourceUsage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_GroupStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_GroupStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_InstanceStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_InstanceStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_StatusResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_StatusResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_BoostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_BoostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_BoostResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_BoostResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_StopBoostRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_StopBoostRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_StopBoostResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_StopBoostResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_AcceptJoinsRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_AcceptJoinsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_AcceptJoinsResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_AcceptJoinsResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_AnnounceRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_AnnounceRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_AnnounceRequest_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_AnnounceRequest_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_AnnounceResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_AnnounceResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_StartServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_StartServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_StartServerResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_StartServerResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_StopServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_StopServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_StopServerResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_StopServerResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_DeleteServerRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_DeleteServerRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_DeleteServerResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_DeleteServerResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_CloudEvent_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_CloudEvent_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_EventInterest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_EventInterest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_RequestError_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_RequestError_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_Ready_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_Ready_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ServerMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ServerMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_OperatorToServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_OperatorToServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_Heartbeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_Heartbeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_PlayerJoinedServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_PlayerJoinedServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_BackendPlayers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_BackendPlayers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_BackendPlayers_PlayersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_BackendPlayers_PlayersEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_PlayerRoster_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_PlayerRoster_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_RosterEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_RosterEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_NetworkState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_NetworkState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_GroupState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_GroupState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_GroupState_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_GroupState_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ServerState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ServerState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ServerState_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ServerState_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ProxyState_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ProxyState_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_ProxyMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_ProxyMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_RegisteredServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_RegisteredServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_FullSync_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_FullSync_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_RegisterServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_RegisterServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_UnregisterServer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_UnregisterServer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_MovePlayer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_MovePlayer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_DrainPlayers_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_DrainPlayers_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_SetReady_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_SetReady_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_spawnery_agent_v1alpha1_OperatorToProxy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_spawnery_agent_v1alpha1_OperatorToProxy_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#spawnery/agent/v1alpha1/agent.proto\022\027s" +
      "pawnery.agent.v1alpha1\"!\n\016ReportInterval" +
      "\022\017\n\007seconds\030\001 \001(\005\"M\n\017SessionDeadline\022\033\n\023" +
      "renew_after_seconds\030\001 \001(\005\022\035\n\025hard_deadli" +
      "ne_seconds\030\002 \001(\005\"D\n\005Hello\022\017\n\007version\030\001 \001" +
      "(\t\022\r\n\005ready\030\002 \001(\010\022\033\n\023read_timeout_millis" +
      "\030\003 \001(\005\"`\n\013PlayerCount\022\017\n\007players\030\001 \001(\005\022\r" +
      "\n\005slots\030\002 \001(\005\022\013\n\003tps\030\003 \001(\001\022\014\n\004mspt\030\004 \001(\001" +
      "\022\026\n\016playable_slots\030\005 \001(\005\"\336\005\n\014CloudReques" +
      "t\022\n\n\002id\030\001 \001(\004\022:\n\007connect\030\002 \001(\0132\'.spawner" +
      "y.agent.v1alpha1.ConnectRequestH\000\0228\n\006ret" +
      "ire\030\003 \001(\0132&.spawnery.agent.v1alpha1.Reti" +
      "reRequestH\000\0226\n\005boost\030\004 \001(\0132%.spawnery.ag" +
      "ent.v1alpha1.BoostRequestH\000\022?\n\nstop_boos" +
      "t\030\005 \001(\0132).spawnery.agent.v1alpha1.StopBo" +
      "ostRequestH\000\022<\n\010announce\030\006 \001(\0132(.spawner" +
      "y.agent.v1alpha1.AnnounceRequestH\000\022C\n\014ac" +
      "cept_joins\030\007 \001(\0132+.spawnery.agent.v1alph" +
      "a1.AcceptJoinsRequestH\000\022C\n\014start_server\030" +
      "\010 \001(\0132+.spawnery.agent.v1alpha1.StartSer" +
      "verRequestH\000\022A\n\013stop_server\030\t \001(\0132*.spaw" +
      "nery.agent.v1alpha1.StopServerRequestH\000\022" +
      "<\n\010unretire\030\n \001(\0132(.spawnery.agent.v1alp" +
      "ha1.UnretireRequestH\000\0228\n\006status\030\013 \001(\0132&." +
      "spawnery.agent.v1alpha1.StatusRequestH\000\022" +
      "E\n\rdelete_server\030\014 \001(\0132,.spawnery.agent." +
      "v1alpha1.DeleteServerRequestH\000B\t\n\007reques" +
      "t\"\213\006\n\rCloudResponse\022\n\n\002id\030\001 \001(\004\0229\n\007conne" +
      "ct\030\002 \001(\0132&.spawnery.agent.v1alpha1.Conne" +
      "ctResultH\000\0226\n\005error\030\003 \001(\0132%.spawnery.age" +
      "nt.v1alpha1.RequestErrorH\000\0227\n\006retire\030\004 \001" +
      "(\0132%.spawnery.agent.v1alpha1.RetireResul" +
      "tH\000\0225\n\005boost\030\005 \001(\0132$.spawnery.agent.v1al" +
      "pha1.BoostResultH\000\022>\n\nstop_boost\030\006 \001(\0132(" +
      ".spawnery.agent.v1alpha1.StopBoostResult" +
      "H\000\022;\n\010announce\030\007 \001(\0132\'.spawnery.agent.v1" +
      "alpha1.AnnounceResultH\000\022B\n\014accept_joins\030" +
      "\010 \001(\0132*.spawnery.agent.v1alpha1.AcceptJo" +
      "insResultH\000\022B\n\014start_server\030\t \001(\0132*.spaw" +
      "nery.agent.v1alpha1.StartServerResultH\000\022" +
      "@\n\013stop_server\030\n \001(\0132).spawnery.agent.v1" +
      "alpha1.StopServerResultH\000\022;\n\010unretire\030\013 " +
      "\001(\0132\'.spawnery.agent.v1alpha1.UnretireRe" +
      "sultH\000\0227\n\006status\030\014 \001(\0132%.spawnery.agent." +
      "v1alpha1.StatusResultH\000\022D\n\rdelete_server" +
      "\030\r \001(\0132+.spawnery.agent.v1alpha1.DeleteS" +
      "erverResultH\000B\010\n\006result\"R\n\016ConnectReques" +
      "t\022\023\n\013player_uuid\030\001 \001(\t\022\020\n\006server\030\002 \001(\tH\000" +
      "\022\017\n\005group\030\003 \001(\tH\000B\010\n\006target\"G\n\rConnectRe" +
      "sult\022\017\n\007ordered\030\001 \001(\010\022\025\n\ralready_there\030\002" +
      " \001(\010\022\016\n\006target\030\003 \001(\t\"\037\n\rRetireRequest\022\016\n" +
      "\006server\030\001 \001(\t\"\036\n\014RetireResult\022\016\n\006server\030" +
      "\001 \001(\t\"!\n\017UnretireRequest\022\016\n\006server\030\001 \001(\t" +
      "\" \n\016UnretireResult\022\016\n\006server\030\001 \001(\t\"\037\n\rSt" +
      "atusRequest\022\016\n\006target\030\001 \001(\t\"\231\002\n\rResource" +
      "Usage\022\033\n\023cpu_used_millicores\030\001 \001(\003\022 \n\030cp" +
      "u_requested_millicores\030\002 \001(\003\022\034\n\024cpu_limi" +
      "t_millicores\030\003 \001(\003\022\025\n\rcpu_unlimited\030\004 \001(" +
      "\010\022\031\n\021memory_used_bytes\030\005 \001(\003\022\036\n\026memory_r" +
      "equested_bytes\030\006 \001(\003\022\032\n\022memory_limit_byt" +
      "es\030\007 \001(\003\022\030\n\020memory_unlimited\030\010 \001(\010\022\014\n\004po" +
      "ds\030\t \001(\005\022\025\n\rpods_measured\030\n \001(\005\"\350\001\n\013Grou" +
      "pStatus\022\014\n\004name\030\001 \001(\t\0226\n\004kind\030\002 \001(\0162(.sp" +
      "awnery.agent.v1alpha1.GroupState.Kind\022\r\n" +
      "\005phase\030\003 \001(\t\022\020\n\010replicas\030\004 \001(\005\022\026\n\016ready_" +
      "replicas\030\005 \001(\005\022\017\n\007players\030\006 \001(\005\022\022\n\nlowes" +
      "t_tps\030\007 \001(\001\0225\n\005usage\030\010 \001(\0132&.spawnery.ag" +
      "ent.v1alpha1.ResourceUsage\"\271\002\n\016InstanceS" +
      "tatus\022\014\n\004name\030\001 \001(\t\022\r\n\005group\030\002 \001(\t\022\r\n\005pr" +
      "oxy\030\003 \001(\010\022\r\n\005phase\030\004 \001(\t\022\r\n\005ready\030\005 \001(\010\022" +
      "\017\n\007players\030\006 \001(\005\022\r\n\005slots\030\007 \001(\005\022\013\n\003tps\030\010" +
      " \001(\001\022\014\n\004mspt\030\t \001(\001\022\023\n\013age_seconds\030\n \001(\003\022" +
      "\020\n\010retiring\030\013 \001(\010\022\014\n\004held\030\014 \001(\010\022\020\n\010drain" +
      "ing\030\r \001(\010\0225\n\005usage\030\016 \001(\0132&.spawnery.agen" +
      "t.v1alpha1.ResourceUsage\022\014\n\004node\030\017 \001(\t\022\026" +
      "\n\016playable_slots\030\020 \001(\005\"\274\002\n\014StatusResult\022" +
      "5\n\005total\030\001 \001(\0132&.spawnery.agent.v1alpha1" +
      ".ResourceUsage\0224\n\006groups\030\002 \003(\0132$.spawner" +
      "y.agent.v1alpha1.GroupStatus\022:\n\tinstance" +
      "s\030\003 \003(\0132\'.spawnery.agent.v1alpha1.Instan" +
      "ceStatus\0225\n\005other\030\004 \001(\0132&.spawnery.agent" +
      ".v1alpha1.ResourceUsage\022\031\n\021metrics_avail" +
      "able\030\005 \001(\010\022\017\n\007players\030\006 \001(\005\022\017\n\007servers\030\007" +
      " \001(\005\022\017\n\007proxies\030\010 \001(\005\"I\n\014BoostRequest\022\r\n" +
      "\005group\030\001 \001(\t\022\020\n\010replicas\030\002 \001(\005\022\030\n\020durati" +
      "on_seconds\030\003 \001(\003\"8\n\013BoostResult\022\020\n\010repli" +
      "cas\030\001 \001(\005\022\027\n\017expires_at_unix\030\002 \001(\003\"!\n\020St" +
      "opBoostRequest\022\r\n\005group\030\001 \001(\t\"\"\n\017StopBoo" +
      "stResult\022\017\n\007removed\030\001 \001(\005\"9\n\022AcceptJoins" +
      "Request\022\016\n\006accept\030\001 \001(\010\022\023\n\013round_ended\030\002" +
      " \001(\010\"\023\n\021AcceptJoinsResult\"\241\001\n\017AnnounceRe" +
      "quest\022\r\n\005state\030\001 \001(\t\022L\n\nattributes\030\002 \003(\013" +
      "28.spawnery.agent.v1alpha1.AnnounceReque" +
      "st.AttributesEntry\0321\n\017AttributesEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\020\n\016Announc" +
      "eResult\"0\n\022StartServerRequest\022\r\n\005group\030\001" +
      " \001(\t\022\013\n\003key\030\002 \001(\t\"<\n\021StartServerResult\022\016" +
      "\n\006server\030\001 \001(\t\022\027\n\017already_running\030\002 \001(\010\"" +
      "#\n\021StopServerRequest\022\016\n\006server\030\001 \001(\t\"\"\n\020" +
      "StopServerResult\022\016\n\006server\030\001 \001(\t\"1\n\023Dele" +
      "teServerRequest\022\r\n\005group\030\001 \001(\t\022\013\n\003key\030\002 " +
      "\001(\t\"3\n\022DeleteServerResult\022\016\n\006server\030\001 \001(" +
      "\t\022\r\n\005world\030\002 \001(\010\"\\\n\nCloudEvent\022\014\n\004kind\030\001" +
      " \001(\t\022\017\n\007subject\030\002 \001(\t\022\r\n\005group\030\003 \001(\t\022\017\n\007" +
      "message\030\004 \001(\t\022\017\n\007warning\030\005 \001(\010\"\037\n\rEventI" +
      "nterest\022\016\n\006wanted\030\001 \001(\010\"\276\001\n\014RequestError" +
      "\022<\n\006reason\030\001 \001(\0162,.spawnery.agent.v1alph" +
      "a1.RequestError.Reason\022\017\n\007message\030\002 \001(\t\"" +
      "_\n\006Reason\022\026\n\022REASON_UNSPECIFIED\020\000\022\r\n\tNOT" +
      "_FOUND\020\001\022\013\n\007REFUSED\020\002\022\020\n\014RATE_LIMITED\020\003\022" +
      "\017\n\013UNAVAILABLE\020\004\"\007\n\005Ready\"\274\002\n\rServerMess" +
      "age\022/\n\005hello\030\001 \001(\0132\036.spawnery.agent.v1al" +
      "pha1.HelloH\000\022/\n\005ready\030\002 \001(\0132\036.spawnery.a" +
      "gent.v1alpha1.ReadyH\000\022<\n\014player_count\030\003 " +
      "\001(\0132$.spawnery.agent.v1alpha1.PlayerCoun" +
      "tH\000\022>\n\rcloud_request\030\004 \001(\0132%.spawnery.ag" +
      "ent.v1alpha1.CloudRequestH\000\022@\n\016event_int" +
      "erest\030\005 \001(\0132&.spawnery.agent.v1alpha1.Ev" +
      "entInterestH\000B\t\n\007message\"\345\002\n\020OperatorToS" +
      "erver\022B\n\017report_interval\030\001 \001(\0132\'.spawner" +
      "y.agent.v1alpha1.ReportIntervalH\000\022D\n\020ses" +
      "sion_deadline\030\002 \001(\0132(.spawnery.agent.v1a" +
      "lpha1.SessionDeadlineH\000\022>\n\rnetwork_state" +
      "\030\003 \001(\0132%.spawnery.agent.v1alpha1.Network" +
      "StateH\000\022@\n\016cloud_response\030\004 \001(\0132&.spawne" +
      "ry.agent.v1alpha1.CloudResponseH\000\022:\n\013clo" +
      "ud_event\030\005 \001(\0132#.spawnery.agent.v1alpha1" +
      ".CloudEventH\000B\t\n\007message\"\013\n\tHeartbeat\"4\n" +
      "\022PlayerJoinedServer\022\016\n\006player\030\001 \001(\t\022\016\n\006s" +
      "erver\030\002 \001(\t\"\207\001\n\016BackendPlayers\022E\n\007player" +
      "s\030\001 \003(\01324.spawnery.agent.v1alpha1.Backen" +
      "dPlayers.PlayersEntry\032.\n\014PlayersEntry\022\013\n" +
      "\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\005:\0028\001\"E\n\014PlayerR" +
      "oster\0225\n\007players\030\001 \003(\0132$.spawnery.agent." +
      "v1alpha1.RosterEntry\"9\n\013RosterEntry\022\014\n\004u" +
      "uid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\016\n\006server\030\003 \001(\t\"" +
      "\374\001\n\014NetworkState\0223\n\006groups\030\001 \003(\0132#.spawn" +
      "ery.agent.v1alpha1.GroupState\0225\n\007servers" +
      "\030\002 \003(\0132$.spawnery.agent.v1alpha1.ServerS" +
      "tate\0225\n\007players\030\003 \003(\0132$.spawnery.agent.v" +
      "1alpha1.RosterEntry\022\023\n\013feed_format\030\004 \001(\t" +
      "\0224\n\007proxies\030\005 \003(\0132#.spawnery.agent.v1alp" +
      "ha1.ProxyState\"\221\003\n\nGroupState\022\014\n\004name\030\001 " +
      "\001(\t\0226\n\004kind\030\002 \001(\0162(.spawnery.agent.v1alp" +
      "ha1.GroupState.Kind\022\020\n\010replicas\030\003 \001(\005\022\026\n" +
      "\016ready_replicas\030\004 \001(\005\022\026\n\016online_players\030" +
      "\005 \001(\005\022\022\n\nfree_slots\030\006 \001(\005\022G\n\nattributes\030" +
      "\007 \003(\01323.spawnery.agent.v1alpha1.GroupSta" +
      "te.AttributesEntry\022\024\n\014display_name\030\010 \001(\t" +
      "\0321\n\017AttributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005valu" +
      "e\030\002 \001(\t:\0028\001\"U\n\004Kind\022\024\n\020KIND_UNSPECIFIED\020" +
      "\000\022\r\n\tEPHEMERAL\020\001\022\016\n\nPERSISTENT\020\002\022\t\n\005PROX" +
      "Y\020\003\022\r\n\tON_DEMAND\020\004\"\322\002\n\013ServerState\022\014\n\004na" +
      "me\030\001 \001(\t\022\r\n\005group\030\002 \001(\t\022\r\n\005phase\030\003 \001(\t\022\017" +
      "\n\007players\030\004 \001(\005\022\r\n\005slots\030\005 \001(\005\022\022\n\nregist" +
      "ered\030\006 \001(\010\022\r\n\005state\030\007 \001(\t\022H\n\nattributes\030" +
      "\010 \003(\01324.spawnery.agent.v1alpha1.ServerSt" +
      "ate.AttributesEntry\022\023\n\013incarnation\030\t \001(\t" +
      "\022\016\n\006number\030\n \001(\005\022\014\n\004held\030\013 \001(\010\022\014\n\004node\030\014" +
      " \001(\t\022\026\n\016playable_slots\030\r \001(\005\0321\n\017Attribut" +
      "esEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"" +
      "i\n\nProxyState\022\014\n\004name\030\001 \001(\t\022\r\n\005group\030\002 \001" +
      "(\t\022\r\n\005ready\030\003 \001(\010\022\020\n\010draining\030\004 \001(\010\022\017\n\007p" +
      "layers\030\005 \001(\005\022\014\n\004node\030\006 \001(\t\"\224\004\n\014ProxyMess" +
      "age\022/\n\005hello\030\001 \001(\0132\036.spawnery.agent.v1al" +
      "pha1.HelloH\000\022<\n\014player_count\030\002 \001(\0132$.spa" +
      "wnery.agent.v1alpha1.PlayerCountH\000\022K\n\024pl" +
      "ayer_joined_server\030\003 \001(\0132+.spawnery.agen" +
      "t.v1alpha1.PlayerJoinedServerH\000\0227\n\theart" +
      "beat\030\004 \001(\0132\".spawnery.agent.v1alpha1.Hea" +
      "rtbeatH\000\022B\n\017backend_players\030\005 \001(\0132\'.spaw" +
      "nery.agent.v1alpha1.BackendPlayersH\000\022>\n\r" +
      "player_roster\030\006 \001(\0132%.spawnery.agent.v1a" +
      "lpha1.PlayerRosterH\000\022>\n\rcloud_request\030\007 " +
      "\001(\0132%.spawnery.agent.v1alpha1.CloudReque" +
      "stH\000\022@\n\016event_interest\030\010 \001(\0132&.spawnery." +
      "agent.v1alpha1.EventInterestH\000B\t\n\007messag" +
      "e\"@\n\020RegisteredServer\022\014\n\004name\030\001 \001(\t\022\017\n\007a" +
      "ddress\030\002 \001(\t\022\r\n\005group\030\003 \001(\t\"F\n\010FullSync\022" +
      ":\n\007servers\030\001 \003(\0132).spawnery.agent.v1alph" +
      "a1.RegisteredServer\"K\n\016RegisterServer\0229\n" +
      "\006server\030\001 \001(\0132).spawnery.agent.v1alpha1." +
      "RegisteredServer\" \n\020UnregisterServer\022\014\n\004" +
      "name\030\001 \001(\t\"8\n\nMovePlayer\022\023\n\013player_uuid\030" +
      "\001 \001(\t\022\025\n\rtarget_server\030\002 \001(\t\"6\n\014DrainPla" +
      "yers\022\023\n\013from_server\030\001 \001(\t\022\021\n\tto_groups\030\002" +
      " \003(\t\"\031\n\010SetReady\022\r\n\005ready\030\001 \001(\010\"\334\005\n\017Oper" +
      "atorToProxy\0226\n\tfull_sync\030\001 \001(\0132!.spawner" +
      "y.agent.v1alpha1.FullSyncH\000\022B\n\017register_" +
      "server\030\002 \001(\0132\'.spawnery.agent.v1alpha1.R" +
      "egisterServerH\000\022F\n\021unregister_server\030\003 \001" +
      "(\0132).spawnery.agent.v1alpha1.UnregisterS" +
      "erverH\000\022>\n\rdrain_players\030\004 \001(\0132%.spawner" +
      "y.agent.v1alpha1.DrainPlayersH\000\022B\n\017repor" +
      "t_interval\030\005 \001(\0132\'.spawnery.agent.v1alph" +
      "a1.ReportIntervalH\000\022D\n\020session_deadline\030" +
      "\006 \001(\0132(.spawnery.agent.v1alpha1.SessionD" +
      "eadlineH\000\0226\n\tset_ready\030\007 \001(\0132!.spawnery." +
      "agent.v1alpha1.SetReadyH\000\022>\n\rnetwork_sta" +
      "te\030\010 \001(\0132%.spawnery.agent.v1alpha1.Netwo" +
      "rkStateH\000\022@\n\016cloud_response\030\t \001(\0132&.spaw" +
      "nery.agent.v1alpha1.CloudResponseH\000\022:\n\013m" +
      "ove_player\030\n \001(\0132#.spawnery.agent.v1alph" +
      "a1.MovePlayerH\000\022:\n\013cloud_event\030\013 \001(\0132#.s" +
      "pawnery.agent.v1alpha1.CloudEventH\000B\t\n\007m" +
      "essage2\333\001\n\014AgentService\022c\n\014ProxySession\022" +
      "%.spawnery.agent.v1alpha1.ProxyMessage\032(" +
      ".spawnery.agent.v1alpha1.OperatorToProxy" +
      "(\0010\001\022f\n\rServerSession\022&.spawnery.agent.v" +
      "1alpha1.ServerMessage\032).spawnery.agent.v" +
      "1alpha1.OperatorToServer(\0010\001BV\n\027cloud.sp" +
      "awnery.agent.pbB\nAgentProtoP\001Z-github.co" +
      "m/spawnery/spawnery/internal/agentpbb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_spawnery_agent_v1alpha1_ReportInterval_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_spawnery_agent_v1alpha1_ReportInterval_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ReportInterval_descriptor,
        new java.lang.String[] { "Seconds", });
    internal_static_spawnery_agent_v1alpha1_SessionDeadline_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_spawnery_agent_v1alpha1_SessionDeadline_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_SessionDeadline_descriptor,
        new java.lang.String[] { "RenewAfterSeconds", "HardDeadlineSeconds", });
    internal_static_spawnery_agent_v1alpha1_Hello_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_spawnery_agent_v1alpha1_Hello_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_Hello_descriptor,
        new java.lang.String[] { "Version", "Ready", "ReadTimeoutMillis", });
    internal_static_spawnery_agent_v1alpha1_PlayerCount_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_spawnery_agent_v1alpha1_PlayerCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_PlayerCount_descriptor,
        new java.lang.String[] { "Players", "Slots", "Tps", "Mspt", "PlayableSlots", });
    internal_static_spawnery_agent_v1alpha1_CloudRequest_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_spawnery_agent_v1alpha1_CloudRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_CloudRequest_descriptor,
        new java.lang.String[] { "Id", "Connect", "Retire", "Boost", "StopBoost", "Announce", "AcceptJoins", "StartServer", "StopServer", "Unretire", "Status", "DeleteServer", "Request", });
    internal_static_spawnery_agent_v1alpha1_CloudResponse_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_spawnery_agent_v1alpha1_CloudResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_CloudResponse_descriptor,
        new java.lang.String[] { "Id", "Connect", "Error", "Retire", "Boost", "StopBoost", "Announce", "AcceptJoins", "StartServer", "StopServer", "Unretire", "Status", "DeleteServer", "Result", });
    internal_static_spawnery_agent_v1alpha1_ConnectRequest_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_spawnery_agent_v1alpha1_ConnectRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ConnectRequest_descriptor,
        new java.lang.String[] { "PlayerUuid", "Server", "Group", "Target", });
    internal_static_spawnery_agent_v1alpha1_ConnectResult_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_spawnery_agent_v1alpha1_ConnectResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ConnectResult_descriptor,
        new java.lang.String[] { "Ordered", "AlreadyThere", "Target", });
    internal_static_spawnery_agent_v1alpha1_RetireRequest_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_spawnery_agent_v1alpha1_RetireRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_RetireRequest_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_spawnery_agent_v1alpha1_RetireResult_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_spawnery_agent_v1alpha1_RetireResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_RetireResult_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_spawnery_agent_v1alpha1_UnretireRequest_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_spawnery_agent_v1alpha1_UnretireRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_UnretireRequest_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_spawnery_agent_v1alpha1_UnretireResult_descriptor =
      getDescriptor().getMessageType(11);
    internal_static_spawnery_agent_v1alpha1_UnretireResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_UnretireResult_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_spawnery_agent_v1alpha1_StatusRequest_descriptor =
      getDescriptor().getMessageType(12);
    internal_static_spawnery_agent_v1alpha1_StatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_StatusRequest_descriptor,
        new java.lang.String[] { "Target", });
    internal_static_spawnery_agent_v1alpha1_ResourceUsage_descriptor =
      getDescriptor().getMessageType(13);
    internal_static_spawnery_agent_v1alpha1_ResourceUsage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ResourceUsage_descriptor,
        new java.lang.String[] { "CpuUsedMillicores", "CpuRequestedMillicores", "CpuLimitMillicores", "CpuUnlimited", "MemoryUsedBytes", "MemoryRequestedBytes", "MemoryLimitBytes", "MemoryUnlimited", "Pods", "PodsMeasured", });
    internal_static_spawnery_agent_v1alpha1_GroupStatus_descriptor =
      getDescriptor().getMessageType(14);
    internal_static_spawnery_agent_v1alpha1_GroupStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_GroupStatus_descriptor,
        new java.lang.String[] { "Name", "Kind", "Phase", "Replicas", "ReadyReplicas", "Players", "LowestTps", "Usage", });
    internal_static_spawnery_agent_v1alpha1_InstanceStatus_descriptor =
      getDescriptor().getMessageType(15);
    internal_static_spawnery_agent_v1alpha1_InstanceStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_InstanceStatus_descriptor,
        new java.lang.String[] { "Name", "Group", "Proxy", "Phase", "Ready", "Players", "Slots", "Tps", "Mspt", "AgeSeconds", "Retiring", "Held", "Draining", "Usage", "Node", "PlayableSlots", });
    internal_static_spawnery_agent_v1alpha1_StatusResult_descriptor =
      getDescriptor().getMessageType(16);
    internal_static_spawnery_agent_v1alpha1_StatusResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_StatusResult_descriptor,
        new java.lang.String[] { "Total", "Groups", "Instances", "Other", "MetricsAvailable", "Players", "Servers", "Proxies", });
    internal_static_spawnery_agent_v1alpha1_BoostRequest_descriptor =
      getDescriptor().getMessageType(17);
    internal_static_spawnery_agent_v1alpha1_BoostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_BoostRequest_descriptor,
        new java.lang.String[] { "Group", "Replicas", "DurationSeconds", });
    internal_static_spawnery_agent_v1alpha1_BoostResult_descriptor =
      getDescriptor().getMessageType(18);
    internal_static_spawnery_agent_v1alpha1_BoostResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_BoostResult_descriptor,
        new java.lang.String[] { "Replicas", "ExpiresAtUnix", });
    internal_static_spawnery_agent_v1alpha1_StopBoostRequest_descriptor =
      getDescriptor().getMessageType(19);
    internal_static_spawnery_agent_v1alpha1_StopBoostRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_StopBoostRequest_descriptor,
        new java.lang.String[] { "Group", });
    internal_static_spawnery_agent_v1alpha1_StopBoostResult_descriptor =
      getDescriptor().getMessageType(20);
    internal_static_spawnery_agent_v1alpha1_StopBoostResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_StopBoostResult_descriptor,
        new java.lang.String[] { "Removed", });
    internal_static_spawnery_agent_v1alpha1_AcceptJoinsRequest_descriptor =
      getDescriptor().getMessageType(21);
    internal_static_spawnery_agent_v1alpha1_AcceptJoinsRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_AcceptJoinsRequest_descriptor,
        new java.lang.String[] { "Accept", "RoundEnded", });
    internal_static_spawnery_agent_v1alpha1_AcceptJoinsResult_descriptor =
      getDescriptor().getMessageType(22);
    internal_static_spawnery_agent_v1alpha1_AcceptJoinsResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_AcceptJoinsResult_descriptor,
        new java.lang.String[] { });
    internal_static_spawnery_agent_v1alpha1_AnnounceRequest_descriptor =
      getDescriptor().getMessageType(23);
    internal_static_spawnery_agent_v1alpha1_AnnounceRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_AnnounceRequest_descriptor,
        new java.lang.String[] { "State", "Attributes", });
    internal_static_spawnery_agent_v1alpha1_AnnounceRequest_AttributesEntry_descriptor =
      internal_static_spawnery_agent_v1alpha1_AnnounceRequest_descriptor.getNestedType(0);
    internal_static_spawnery_agent_v1alpha1_AnnounceRequest_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_AnnounceRequest_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spawnery_agent_v1alpha1_AnnounceResult_descriptor =
      getDescriptor().getMessageType(24);
    internal_static_spawnery_agent_v1alpha1_AnnounceResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_AnnounceResult_descriptor,
        new java.lang.String[] { });
    internal_static_spawnery_agent_v1alpha1_StartServerRequest_descriptor =
      getDescriptor().getMessageType(25);
    internal_static_spawnery_agent_v1alpha1_StartServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_StartServerRequest_descriptor,
        new java.lang.String[] { "Group", "Key", });
    internal_static_spawnery_agent_v1alpha1_StartServerResult_descriptor =
      getDescriptor().getMessageType(26);
    internal_static_spawnery_agent_v1alpha1_StartServerResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_StartServerResult_descriptor,
        new java.lang.String[] { "Server", "AlreadyRunning", });
    internal_static_spawnery_agent_v1alpha1_StopServerRequest_descriptor =
      getDescriptor().getMessageType(27);
    internal_static_spawnery_agent_v1alpha1_StopServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_StopServerRequest_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_spawnery_agent_v1alpha1_StopServerResult_descriptor =
      getDescriptor().getMessageType(28);
    internal_static_spawnery_agent_v1alpha1_StopServerResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_StopServerResult_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_spawnery_agent_v1alpha1_DeleteServerRequest_descriptor =
      getDescriptor().getMessageType(29);
    internal_static_spawnery_agent_v1alpha1_DeleteServerRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_DeleteServerRequest_descriptor,
        new java.lang.String[] { "Group", "Key", });
    internal_static_spawnery_agent_v1alpha1_DeleteServerResult_descriptor =
      getDescriptor().getMessageType(30);
    internal_static_spawnery_agent_v1alpha1_DeleteServerResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_DeleteServerResult_descriptor,
        new java.lang.String[] { "Server", "World", });
    internal_static_spawnery_agent_v1alpha1_CloudEvent_descriptor =
      getDescriptor().getMessageType(31);
    internal_static_spawnery_agent_v1alpha1_CloudEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_CloudEvent_descriptor,
        new java.lang.String[] { "Kind", "Subject", "Group", "Message", "Warning", });
    internal_static_spawnery_agent_v1alpha1_EventInterest_descriptor =
      getDescriptor().getMessageType(32);
    internal_static_spawnery_agent_v1alpha1_EventInterest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_EventInterest_descriptor,
        new java.lang.String[] { "Wanted", });
    internal_static_spawnery_agent_v1alpha1_RequestError_descriptor =
      getDescriptor().getMessageType(33);
    internal_static_spawnery_agent_v1alpha1_RequestError_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_RequestError_descriptor,
        new java.lang.String[] { "Reason", "Message", });
    internal_static_spawnery_agent_v1alpha1_Ready_descriptor =
      getDescriptor().getMessageType(34);
    internal_static_spawnery_agent_v1alpha1_Ready_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_Ready_descriptor,
        new java.lang.String[] { });
    internal_static_spawnery_agent_v1alpha1_ServerMessage_descriptor =
      getDescriptor().getMessageType(35);
    internal_static_spawnery_agent_v1alpha1_ServerMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ServerMessage_descriptor,
        new java.lang.String[] { "Hello", "Ready", "PlayerCount", "CloudRequest", "EventInterest", "Message", });
    internal_static_spawnery_agent_v1alpha1_OperatorToServer_descriptor =
      getDescriptor().getMessageType(36);
    internal_static_spawnery_agent_v1alpha1_OperatorToServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_OperatorToServer_descriptor,
        new java.lang.String[] { "ReportInterval", "SessionDeadline", "NetworkState", "CloudResponse", "CloudEvent", "Message", });
    internal_static_spawnery_agent_v1alpha1_Heartbeat_descriptor =
      getDescriptor().getMessageType(37);
    internal_static_spawnery_agent_v1alpha1_Heartbeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_Heartbeat_descriptor,
        new java.lang.String[] { });
    internal_static_spawnery_agent_v1alpha1_PlayerJoinedServer_descriptor =
      getDescriptor().getMessageType(38);
    internal_static_spawnery_agent_v1alpha1_PlayerJoinedServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_PlayerJoinedServer_descriptor,
        new java.lang.String[] { "Player", "Server", });
    internal_static_spawnery_agent_v1alpha1_BackendPlayers_descriptor =
      getDescriptor().getMessageType(39);
    internal_static_spawnery_agent_v1alpha1_BackendPlayers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_BackendPlayers_descriptor,
        new java.lang.String[] { "Players", });
    internal_static_spawnery_agent_v1alpha1_BackendPlayers_PlayersEntry_descriptor =
      internal_static_spawnery_agent_v1alpha1_BackendPlayers_descriptor.getNestedType(0);
    internal_static_spawnery_agent_v1alpha1_BackendPlayers_PlayersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_BackendPlayers_PlayersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spawnery_agent_v1alpha1_PlayerRoster_descriptor =
      getDescriptor().getMessageType(40);
    internal_static_spawnery_agent_v1alpha1_PlayerRoster_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_PlayerRoster_descriptor,
        new java.lang.String[] { "Players", });
    internal_static_spawnery_agent_v1alpha1_RosterEntry_descriptor =
      getDescriptor().getMessageType(41);
    internal_static_spawnery_agent_v1alpha1_RosterEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_RosterEntry_descriptor,
        new java.lang.String[] { "Uuid", "Name", "Server", });
    internal_static_spawnery_agent_v1alpha1_NetworkState_descriptor =
      getDescriptor().getMessageType(42);
    internal_static_spawnery_agent_v1alpha1_NetworkState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_NetworkState_descriptor,
        new java.lang.String[] { "Groups", "Servers", "Players", "FeedFormat", "Proxies", });
    internal_static_spawnery_agent_v1alpha1_GroupState_descriptor =
      getDescriptor().getMessageType(43);
    internal_static_spawnery_agent_v1alpha1_GroupState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_GroupState_descriptor,
        new java.lang.String[] { "Name", "Kind", "Replicas", "ReadyReplicas", "OnlinePlayers", "FreeSlots", "Attributes", "DisplayName", });
    internal_static_spawnery_agent_v1alpha1_GroupState_AttributesEntry_descriptor =
      internal_static_spawnery_agent_v1alpha1_GroupState_descriptor.getNestedType(0);
    internal_static_spawnery_agent_v1alpha1_GroupState_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_GroupState_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spawnery_agent_v1alpha1_ServerState_descriptor =
      getDescriptor().getMessageType(44);
    internal_static_spawnery_agent_v1alpha1_ServerState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ServerState_descriptor,
        new java.lang.String[] { "Name", "Group", "Phase", "Players", "Slots", "Registered", "State", "Attributes", "Incarnation", "Number", "Held", "Node", "PlayableSlots", });
    internal_static_spawnery_agent_v1alpha1_ServerState_AttributesEntry_descriptor =
      internal_static_spawnery_agent_v1alpha1_ServerState_descriptor.getNestedType(0);
    internal_static_spawnery_agent_v1alpha1_ServerState_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ServerState_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_spawnery_agent_v1alpha1_ProxyState_descriptor =
      getDescriptor().getMessageType(45);
    internal_static_spawnery_agent_v1alpha1_ProxyState_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ProxyState_descriptor,
        new java.lang.String[] { "Name", "Group", "Ready", "Draining", "Players", "Node", });
    internal_static_spawnery_agent_v1alpha1_ProxyMessage_descriptor =
      getDescriptor().getMessageType(46);
    internal_static_spawnery_agent_v1alpha1_ProxyMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_ProxyMessage_descriptor,
        new java.lang.String[] { "Hello", "PlayerCount", "PlayerJoinedServer", "Heartbeat", "BackendPlayers", "PlayerRoster", "CloudRequest", "EventInterest", "Message", });
    internal_static_spawnery_agent_v1alpha1_RegisteredServer_descriptor =
      getDescriptor().getMessageType(47);
    internal_static_spawnery_agent_v1alpha1_RegisteredServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_RegisteredServer_descriptor,
        new java.lang.String[] { "Name", "Address", "Group", });
    internal_static_spawnery_agent_v1alpha1_FullSync_descriptor =
      getDescriptor().getMessageType(48);
    internal_static_spawnery_agent_v1alpha1_FullSync_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_FullSync_descriptor,
        new java.lang.String[] { "Servers", });
    internal_static_spawnery_agent_v1alpha1_RegisterServer_descriptor =
      getDescriptor().getMessageType(49);
    internal_static_spawnery_agent_v1alpha1_RegisterServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_RegisterServer_descriptor,
        new java.lang.String[] { "Server", });
    internal_static_spawnery_agent_v1alpha1_UnregisterServer_descriptor =
      getDescriptor().getMessageType(50);
    internal_static_spawnery_agent_v1alpha1_UnregisterServer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_UnregisterServer_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_spawnery_agent_v1alpha1_MovePlayer_descriptor =
      getDescriptor().getMessageType(51);
    internal_static_spawnery_agent_v1alpha1_MovePlayer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_MovePlayer_descriptor,
        new java.lang.String[] { "PlayerUuid", "TargetServer", });
    internal_static_spawnery_agent_v1alpha1_DrainPlayers_descriptor =
      getDescriptor().getMessageType(52);
    internal_static_spawnery_agent_v1alpha1_DrainPlayers_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_DrainPlayers_descriptor,
        new java.lang.String[] { "FromServer", "ToGroups", });
    internal_static_spawnery_agent_v1alpha1_SetReady_descriptor =
      getDescriptor().getMessageType(53);
    internal_static_spawnery_agent_v1alpha1_SetReady_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_SetReady_descriptor,
        new java.lang.String[] { "Ready", });
    internal_static_spawnery_agent_v1alpha1_OperatorToProxy_descriptor =
      getDescriptor().getMessageType(54);
    internal_static_spawnery_agent_v1alpha1_OperatorToProxy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_spawnery_agent_v1alpha1_OperatorToProxy_descriptor,
        new java.lang.String[] { "FullSync", "RegisterServer", "UnregisterServer", "DrainPlayers", "ReportInterval", "SessionDeadline", "SetReady", "NetworkState", "CloudResponse", "MovePlayer", "CloudEvent", "Message", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
