// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface DeleteServerResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.DeleteServerResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The member's name, as StartServerResult carries it.
   * </pre>
   *
   * <code>string server = 1;</code>
   * @return The server.
   */
  java.lang.String getServer();
  /**
   * <pre>
   * The member's name, as StartServerResult carries it.
   * </pre>
   *
   * <code>string server = 1;</code>
   * @return The bytes for server.
   */
  com.google.protobuf.ByteString
      getServerBytes();

  /**
   * <pre>
   * True when a world claim was deleted; false when there was only a server.
   * </pre>
   *
   * <code>bool world = 2;</code>
   * @return The world.
   */
  boolean getWorld();
}
