// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface GroupStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.GroupStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
   * @return The enum numeric value on the wire for kind.
   */
  int getKindValue();
  /**
   * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
   * @return The kind.
   */
  cloud.spawnery.agent.pb.GroupState.Kind getKind();

  /**
   * <code>string phase = 3;</code>
   * @return The phase.
   */
  java.lang.String getPhase();
  /**
   * <code>string phase = 3;</code>
   * @return The bytes for phase.
   */
  com.google.protobuf.ByteString
      getPhaseBytes();

  /**
   * <code>int32 replicas = 4;</code>
   * @return The replicas.
   */
  int getReplicas();

  /**
   * <code>int32 ready_replicas = 5;</code>
   * @return The readyReplicas.
   */
  int getReadyReplicas();

  /**
   * <code>int32 players = 6;</code>
   * @return The players.
   */
  int getPlayers();

  /**
   * <pre>
   * The lowest TPS among the group's servers that reported one; 0 if none did.
   * </pre>
   *
   * <code>double lowest_tps = 7;</code>
   * @return The lowestTps.
   */
  double getLowestTps();

  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
   * @return Whether the usage field is set.
   */
  boolean hasUsage();
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
   * @return The usage.
   */
  cloud.spawnery.agent.pb.ResourceUsage getUsage();
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
   */
  cloud.spawnery.agent.pb.ResourceUsageOrBuilder getUsageOrBuilder();
}
