// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * Protobuf type {@code spawnery.agent.v1alpha1.GroupStatus}
 */
@com.google.protobuf.Generated
public final class GroupStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.GroupStatus)
    GroupStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "GroupStatus");
  }
  // Use GroupStatus.newBuilder() to construct.
  private GroupStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private GroupStatus() {
    name_ = "";
    kind_ = 0;
    phase_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_GroupStatus_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_GroupStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_GroupStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.GroupStatus.class, cloud.spawnery.agent.pb.GroupStatus.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KIND_FIELD_NUMBER = 2;
  private int kind_ = 0;
  /**
   * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
   * @return The enum numeric value on the wire for kind.
   */
  @java.lang.Override public int getKindValue() {
    return kind_;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
   * @return The kind.
   */
  @java.lang.Override public cloud.spawnery.agent.pb.GroupState.Kind getKind() {
    cloud.spawnery.agent.pb.GroupState.Kind result = cloud.spawnery.agent.pb.GroupState.Kind.forNumber(kind_);
    return result == null ? cloud.spawnery.agent.pb.GroupState.Kind.UNRECOGNIZED : result;
  }

  public static final int PHASE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object phase_ = "";
  /**
   * <code>string phase = 3;</code>
   * @return The phase.
   */
  @java.lang.Override
  public java.lang.String getPhase() {
    java.lang.Object ref = phase_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phase_ = s;
      return s;
    }
  }
  /**
   * <code>string phase = 3;</code>
   * @return The bytes for phase.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhaseBytes() {
    java.lang.Object ref = phase_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phase_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int REPLICAS_FIELD_NUMBER = 4;
  private int replicas_ = 0;
  /**
   * <code>int32 replicas = 4;</code>
   * @return The replicas.
   */
  @java.lang.Override
  public int getReplicas() {
    return replicas_;
  }

  public static final int READY_REPLICAS_FIELD_NUMBER = 5;
  private int readyReplicas_ = 0;
  /**
   * <code>int32 ready_replicas = 5;</code>
   * @return The readyReplicas.
   */
  @java.lang.Override
  public int getReadyReplicas() {
    return readyReplicas_;
  }

  public static final int PLAYERS_FIELD_NUMBER = 6;
  private int players_ = 0;
  /**
   * <code>int32 players = 6;</code>
   * @return The players.
   */
  @java.lang.Override
  public int getPlayers() {
    return players_;
  }

  public static final int LOWEST_TPS_FIELD_NUMBER = 7;
  private double lowestTps_ = 0D;
  /**
   * <pre>
   * The lowest TPS among the group's servers that reported one; 0 if none did.
   * </pre>
   *
   * <code>double lowest_tps = 7;</code>
   * @return The lowestTps.
   */
  @java.lang.Override
  public double getLowestTps() {
    return lowestTps_;
  }

  public static final int USAGE_FIELD_NUMBER = 8;
  private cloud.spawnery.agent.pb.ResourceUsage usage_;
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
   * @return Whether the usage field is set.
   */
  @java.lang.Override
  public boolean hasUsage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
   * @return The usage.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsage getUsage() {
    return usage_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : usage_;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsageOrBuilder getUsageOrBuilder() {
    return usage_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : usage_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (kind_ != cloud.spawnery.agent.pb.GroupState.Kind.KIND_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, kind_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phase_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, phase_);
    }
    if (replicas_ != 0) {
      output.writeInt32(4, replicas_);
    }
    if (readyReplicas_ != 0) {
      output.writeInt32(5, readyReplicas_);
    }
    if (players_ != 0) {
      output.writeInt32(6, players_);
    }
    if (java.lang.Double.doubleToRawLongBits(lowestTps_) != 0) {
      output.writeDouble(7, lowestTps_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(8, getUsage());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (kind_ != cloud.spawnery.agent.pb.GroupState.Kind.KIND_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, kind_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phase_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, phase_);
    }
    if (replicas_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, replicas_);
    }
    if (readyReplicas_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, readyReplicas_);
    }
    if (players_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, players_);
    }
    if (java.lang.Double.doubleToRawLongBits(lowestTps_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(7, lowestTps_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getUsage());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.GroupStatus)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.GroupStatus other = (cloud.spawnery.agent.pb.GroupStatus) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (kind_ != other.kind_) return false;
    if (!getPhase()
        .equals(other.getPhase())) return false;
    if (getReplicas()
        != other.getReplicas()) return false;
    if (getReadyReplicas()
        != other.getReadyReplicas()) return false;
    if (getPlayers()
        != other.getPlayers()) return false;
    if (java.lang.Double.doubleToLongBits(getLowestTps())
        != java.lang.Double.doubleToLongBits(
            other.getLowestTps())) return false;
    if (hasUsage() != other.hasUsage()) return false;
    if (hasUsage()) {
      if (!getUsage()
          .equals(other.getUsage())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + KIND_FIELD_NUMBER;
    hash = (53 * hash) + kind_;
    hash = (37 * hash) + PHASE_FIELD_NUMBER;
    hash = (53 * hash) + getPhase().hashCode();
    hash = (37 * hash) + REPLICAS_FIELD_NUMBER;
    hash = (53 * hash) + getReplicas();
    hash = (37 * hash) + READY_REPLICAS_FIELD_NUMBER;
    hash = (53 * hash) + getReadyReplicas();
    hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
    hash = (53 * hash) + getPlayers();
    hash = (37 * hash) + LOWEST_TPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getLowestTps()));
    if (hasUsage()) {
      hash = (37 * hash) + USAGE_FIELD_NUMBER;
      hash = (53 * hash) + getUsage().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.GroupStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.GroupStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.GroupStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.GroupStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code spawnery.agent.v1alpha1.GroupStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.GroupStatus)
      cloud.spawnery.agent.pb.GroupStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_GroupStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_GroupStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.GroupStatus.class, cloud.spawnery.agent.pb.GroupStatus.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.GroupStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetUsageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      kind_ = 0;
      phase_ = "";
      replicas_ = 0;
      readyReplicas_ = 0;
      players_ = 0;
      lowestTps_ = 0D;
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_GroupStatus_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.GroupStatus getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.GroupStatus.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.GroupStatus build() {
      cloud.spawnery.agent.pb.GroupStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.GroupStatus buildPartial() {
      cloud.spawnery.agent.pb.GroupStatus result = new cloud.spawnery.agent.pb.GroupStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.spawnery.agent.pb.GroupStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.kind_ = kind_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.phase_ = phase_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.replicas_ = replicas_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.readyReplicas_ = readyReplicas_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.players_ = players_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.lowestTps_ = lowestTps_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.usage_ = usageBuilder_ == null
            ? usage_
            : usageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.GroupStatus) {
        return mergeFrom((cloud.spawnery.agent.pb.GroupStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.GroupStatus other) {
      if (other == cloud.spawnery.agent.pb.GroupStatus.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.kind_ != 0) {
        setKindValue(other.getKindValue());
      }
      if (!other.getPhase().isEmpty()) {
        phase_ = other.phase_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.getReplicas() != 0) {
        setReplicas(other.getReplicas());
      }
      if (other.getReadyReplicas() != 0) {
        setReadyReplicas(other.getReadyReplicas());
      }
      if (other.getPlayers() != 0) {
        setPlayers(other.getPlayers());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getLowestTps()) != 0) {
        setLowestTps(other.getLowestTps());
      }
      if (other.hasUsage()) {
        mergeUsage(other.getUsage());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              kind_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 26: {
              phase_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              replicas_ = input.readInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              readyReplicas_ = input.readInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              players_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 57: {
              lowestTps_ = input.readDouble();
              bitField0_ |= 0x00000040;
              break;
            } // case 57
            case 66: {
              input.readMessage(
                  internalGetUsageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private int kind_ = 0;
    /**
     * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
     * @return The enum numeric value on the wire for kind.
     */
    @java.lang.Override public int getKindValue() {
      return kind_;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
     * @param value The enum numeric value on the wire for kind to set.
     * @return This builder for chaining.
     */
    public Builder setKindValue(int value) {
      kind_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
     * @return The kind.
     */
    @java.lang.Override
    public cloud.spawnery.agent.pb.GroupState.Kind getKind() {
      cloud.spawnery.agent.pb.GroupState.Kind result = cloud.spawnery.agent.pb.GroupState.Kind.forNumber(kind_);
      return result == null ? cloud.spawnery.agent.pb.GroupState.Kind.UNRECOGNIZED : result;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
     * @param value The kind to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setKind(cloud.spawnery.agent.pb.GroupState.Kind value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      kind_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.GroupState.Kind kind = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearKind() {
      bitField0_ = (bitField0_ & ~0x00000002);
      kind_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object phase_ = "";
    /**
     * <code>string phase = 3;</code>
     * @return The phase.
     */
    public java.lang.String getPhase() {
      java.lang.Object ref = phase_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phase_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string phase = 3;</code>
     * @return The bytes for phase.
     */
    public com.google.protobuf.ByteString
        getPhaseBytes() {
      java.lang.Object ref = phase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string phase = 3;</code>
     * @param value The phase to set.
     * @return This builder for chaining.
     */
    public Builder setPhase(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      phase_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string phase = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhase() {
      phase_ = getDefaultInstance().getPhase();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string phase = 3;</code>
     * @param value The bytes for phase to set.
     * @return This builder for chaining.
     */
    public Builder setPhaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      phase_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int replicas_ ;
    /**
     * <code>int32 replicas = 4;</code>
     * @return The replicas.
     */
    @java.lang.Override
    public int getReplicas() {
      return replicas_;
    }
    /**
     * <code>int32 replicas = 4;</code>
     * @param value The replicas to set.
     * @return This builder for chaining.
     */
    public Builder setReplicas(int value) {

      replicas_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>int32 replicas = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearReplicas() {
      bitField0_ = (bitField0_ & ~0x00000008);
      replicas_ = 0;
      onChanged();
      return this;
    }

    private int readyReplicas_ ;
    /**
     * <code>int32 ready_replicas = 5;</code>
     * @return The readyReplicas.
     */
    @java.lang.Override
    public int getReadyReplicas() {
      return readyReplicas_;
    }
    /**
     * <code>int32 ready_replicas = 5;</code>
     * @param value The readyReplicas to set.
     * @return This builder for chaining.
     */
    public Builder setReadyReplicas(int value) {

      readyReplicas_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int32 ready_replicas = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadyReplicas() {
      bitField0_ = (bitField0_ & ~0x00000010);
      readyReplicas_ = 0;
      onChanged();
      return this;
    }

    private int players_ ;
    /**
     * <code>int32 players = 6;</code>
     * @return The players.
     */
    @java.lang.Override
    public int getPlayers() {
      return players_;
    }
    /**
     * <code>int32 players = 6;</code>
     * @param value The players to set.
     * @return This builder for chaining.
     */
    public Builder setPlayers(int value) {

      players_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 players = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayers() {
      bitField0_ = (bitField0_ & ~0x00000020);
      players_ = 0;
      onChanged();
      return this;
    }

    private double lowestTps_ ;
    /**
     * <pre>
     * The lowest TPS among the group's servers that reported one; 0 if none did.
     * </pre>
     *
     * <code>double lowest_tps = 7;</code>
     * @return The lowestTps.
     */
    @java.lang.Override
    public double getLowestTps() {
      return lowestTps_;
    }
    /**
     * <pre>
     * The lowest TPS among the group's servers that reported one; 0 if none did.
     * </pre>
     *
     * <code>double lowest_tps = 7;</code>
     * @param value The lowestTps to set.
     * @return This builder for chaining.
     */
    public Builder setLowestTps(double value) {

      lowestTps_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The lowest TPS among the group's servers that reported one; 0 if none did.
     * </pre>
     *
     * <code>double lowest_tps = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLowestTps() {
      bitField0_ = (bitField0_ & ~0x00000040);
      lowestTps_ = 0D;
      onChanged();
      return this;
    }

    private cloud.spawnery.agent.pb.ResourceUsage usage_;
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder> usageBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     * @return Whether the usage field is set.
     */
    public boolean hasUsage() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     * @return The usage.
     */
    public cloud.spawnery.agent.pb.ResourceUsage getUsage() {
      if (usageBuilder_ == null) {
        return usage_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : usage_;
      } else {
        return usageBuilder_.getMessage();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     */
    public Builder setUsage(cloud.spawnery.agent.pb.ResourceUsage value) {
      if (usageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        usage_ = value;
      } else {
        usageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     */
    public Builder setUsage(
        cloud.spawnery.agent.pb.ResourceUsage.Builder builderForValue) {
      if (usageBuilder_ == null) {
        usage_ = builderForValue.build();
      } else {
        usageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     */
    public Builder mergeUsage(cloud.spawnery.agent.pb.ResourceUsage value) {
      if (usageBuilder_ == null) {
        if (((bitField0_ & 0x00000080) != 0) &&
          usage_ != null &&
          usage_ != cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance()) {
          getUsageBuilder().mergeFrom(value);
        } else {
          usage_ = value;
        }
      } else {
        usageBuilder_.mergeFrom(value);
      }
      if (usage_ != null) {
        bitField0_ |= 0x00000080;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     */
    public Builder clearUsage() {
      bitField0_ = (bitField0_ & ~0x00000080);
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     */
    public cloud.spawnery.agent.pb.ResourceUsage.Builder getUsageBuilder() {
      bitField0_ |= 0x00000080;
      onChanged();
      return internalGetUsageFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     */
    public cloud.spawnery.agent.pb.ResourceUsageOrBuilder getUsageOrBuilder() {
      if (usageBuilder_ != null) {
        return usageBuilder_.getMessageOrBuilder();
      } else {
        return usage_ == null ?
            cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : usage_;
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder> 
        internalGetUsageFieldBuilder() {
      if (usageBuilder_ == null) {
        usageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder>(
                getUsage(),
                getParentForChildren(),
                isClean());
        usage_ = null;
      }
      return usageBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.GroupStatus)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.GroupStatus)
  private static final cloud.spawnery.agent.pb.GroupStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.GroupStatus();
  }

  public static cloud.spawnery.agent.pb.GroupStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GroupStatus>
      PARSER = new com.google.protobuf.AbstractParser<GroupStatus>() {
    @java.lang.Override
    public GroupStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GroupStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GroupStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.GroupStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

