// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * Protobuf type {@code spawnery.agent.v1alpha1.InstanceStatus}
 */
@com.google.protobuf.Generated
public final class InstanceStatus extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.InstanceStatus)
    InstanceStatusOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "InstanceStatus");
  }
  // Use InstanceStatus.newBuilder() to construct.
  private InstanceStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private InstanceStatus() {
    name_ = "";
    group_ = "";
    phase_ = "";
    node_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_InstanceStatus_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_InstanceStatus_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_InstanceStatus_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.InstanceStatus.class, cloud.spawnery.agent.pb.InstanceStatus.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GROUP_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object group_ = "";
  /**
   * <code>string group = 2;</code>
   * @return The group.
   */
  @java.lang.Override
  public java.lang.String getGroup() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      group_ = s;
      return s;
    }
  }
  /**
   * <code>string group = 2;</code>
   * @return The bytes for group.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGroupBytes() {
    java.lang.Object ref = group_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      group_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PROXY_FIELD_NUMBER = 3;
  private boolean proxy_ = false;
  /**
   * <code>bool proxy = 3;</code>
   * @return The proxy.
   */
  @java.lang.Override
  public boolean getProxy() {
    return proxy_;
  }

  public static final int PHASE_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object phase_ = "";
  /**
   * <pre>
   * A server's phase; empty for a proxy, whose state is ready and draining.
   * </pre>
   *
   * <code>string phase = 4;</code>
   * @return The phase.
   */
  @java.lang.Override
  public java.lang.String getPhase() {
    java.lang.Object ref = phase_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      phase_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * A server's phase; empty for a proxy, whose state is ready and draining.
   * </pre>
   *
   * <code>string phase = 4;</code>
   * @return The bytes for phase.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPhaseBytes() {
    java.lang.Object ref = phase_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      phase_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int READY_FIELD_NUMBER = 5;
  private boolean ready_ = false;
  /**
   * <code>bool ready = 5;</code>
   * @return The ready.
   */
  @java.lang.Override
  public boolean getReady() {
    return ready_;
  }

  public static final int PLAYERS_FIELD_NUMBER = 6;
  private int players_ = 0;
  /**
   * <code>int32 players = 6;</code>
   * @return The players.
   */
  @java.lang.Override
  public int getPlayers() {
    return players_;
  }

  public static final int SLOTS_FIELD_NUMBER = 7;
  private int slots_ = 0;
  /**
   * <code>int32 slots = 7;</code>
   * @return The slots.
   */
  @java.lang.Override
  public int getSlots() {
    return slots_;
  }

  public static final int TPS_FIELD_NUMBER = 8;
  private double tps_ = 0D;
  /**
   * <pre>
   * 0 = not reported
   * </pre>
   *
   * <code>double tps = 8;</code>
   * @return The tps.
   */
  @java.lang.Override
  public double getTps() {
    return tps_;
  }

  public static final int MSPT_FIELD_NUMBER = 9;
  private double mspt_ = 0D;
  /**
   * <pre>
   * 0 = not reported
   * </pre>
   *
   * <code>double mspt = 9;</code>
   * @return The mspt.
   */
  @java.lang.Override
  public double getMspt() {
    return mspt_;
  }

  public static final int AGE_SECONDS_FIELD_NUMBER = 10;
  private long ageSeconds_ = 0L;
  /**
   * <code>int64 age_seconds = 10;</code>
   * @return The ageSeconds.
   */
  @java.lang.Override
  public long getAgeSeconds() {
    return ageSeconds_;
  }

  public static final int RETIRING_FIELD_NUMBER = 11;
  private boolean retiring_ = false;
  /**
   * <code>bool retiring = 11;</code>
   * @return The retiring.
   */
  @java.lang.Override
  public boolean getRetiring() {
    return retiring_;
  }

  public static final int HELD_FIELD_NUMBER = 12;
  private boolean held_ = false;
  /**
   * <code>bool held = 12;</code>
   * @return The held.
   */
  @java.lang.Override
  public boolean getHeld() {
    return held_;
  }

  public static final int DRAINING_FIELD_NUMBER = 13;
  private boolean draining_ = false;
  /**
   * <code>bool draining = 13;</code>
   * @return The draining.
   */
  @java.lang.Override
  public boolean getDraining() {
    return draining_;
  }

  public static final int USAGE_FIELD_NUMBER = 14;
  private cloud.spawnery.agent.pb.ResourceUsage usage_;
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
   * @return Whether the usage field is set.
   */
  @java.lang.Override
  public boolean hasUsage() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
   * @return The usage.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsage getUsage() {
    return usage_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : usage_;
  }
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsageOrBuilder getUsageOrBuilder() {
    return usage_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : usage_;
  }

  public static final int NODE_FIELD_NUMBER = 15;
  @SuppressWarnings("serial")
  private volatile java.lang.Object node_ = "";
  /**
   * <pre>
   * as ServerState.node
   * </pre>
   *
   * <code>string node = 15;</code>
   * @return The node.
   */
  @java.lang.Override
  public java.lang.String getNode() {
    java.lang.Object ref = node_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      node_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * as ServerState.node
   * </pre>
   *
   * <code>string node = 15;</code>
   * @return The bytes for node.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNodeBytes() {
    java.lang.Object ref = node_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      node_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLAYABLE_SLOTS_FIELD_NUMBER = 16;
  private int playableSlots_ = 0;
  /**
   * <pre>
   * as ServerState.playable_slots
   * </pre>
   *
   * <code>int32 playable_slots = 16;</code>
   * @return The playableSlots.
   */
  @java.lang.Override
  public int getPlayableSlots() {
    return playableSlots_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(group_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, group_);
    }
    if (proxy_ != false) {
      output.writeBool(3, proxy_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phase_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, phase_);
    }
    if (ready_ != false) {
      output.writeBool(5, ready_);
    }
    if (players_ != 0) {
      output.writeInt32(6, players_);
    }
    if (slots_ != 0) {
      output.writeInt32(7, slots_);
    }
    if (java.lang.Double.doubleToRawLongBits(tps_) != 0) {
      output.writeDouble(8, tps_);
    }
    if (java.lang.Double.doubleToRawLongBits(mspt_) != 0) {
      output.writeDouble(9, mspt_);
    }
    if (ageSeconds_ != 0L) {
      output.writeInt64(10, ageSeconds_);
    }
    if (retiring_ != false) {
      output.writeBool(11, retiring_);
    }
    if (held_ != false) {
      output.writeBool(12, held_);
    }
    if (draining_ != false) {
      output.writeBool(13, draining_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(14, getUsage());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(node_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 15, node_);
    }
    if (playableSlots_ != 0) {
      output.writeInt32(16, playableSlots_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(group_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, group_);
    }
    if (proxy_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, proxy_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(phase_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, phase_);
    }
    if (ready_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, ready_);
    }
    if (players_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, players_);
    }
    if (slots_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, slots_);
    }
    if (java.lang.Double.doubleToRawLongBits(tps_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(8, tps_);
    }
    if (java.lang.Double.doubleToRawLongBits(mspt_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(9, mspt_);
    }
    if (ageSeconds_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(10, ageSeconds_);
    }
    if (retiring_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(11, retiring_);
    }
    if (held_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(12, held_);
    }
    if (draining_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(13, draining_);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(14, getUsage());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(node_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(15, node_);
    }
    if (playableSlots_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(16, playableSlots_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.InstanceStatus)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.InstanceStatus other = (cloud.spawnery.agent.pb.InstanceStatus) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getGroup()
        .equals(other.getGroup())) return false;
    if (getProxy()
        != other.getProxy()) return false;
    if (!getPhase()
        .equals(other.getPhase())) return false;
    if (getReady()
        != other.getReady()) return false;
    if (getPlayers()
        != other.getPlayers()) return false;
    if (getSlots()
        != other.getSlots()) return false;
    if (java.lang.Double.doubleToLongBits(getTps())
        != java.lang.Double.doubleToLongBits(
            other.getTps())) return false;
    if (java.lang.Double.doubleToLongBits(getMspt())
        != java.lang.Double.doubleToLongBits(
            other.getMspt())) return false;
    if (getAgeSeconds()
        != other.getAgeSeconds()) return false;
    if (getRetiring()
        != other.getRetiring()) return false;
    if (getHeld()
        != other.getHeld()) return false;
    if (getDraining()
        != other.getDraining()) return false;
    if (hasUsage() != other.hasUsage()) return false;
    if (hasUsage()) {
      if (!getUsage()
          .equals(other.getUsage())) return false;
    }
    if (!getNode()
        .equals(other.getNode())) return false;
    if (getPlayableSlots()
        != other.getPlayableSlots()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + GROUP_FIELD_NUMBER;
    hash = (53 * hash) + getGroup().hashCode();
    hash = (37 * hash) + PROXY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getProxy());
    hash = (37 * hash) + PHASE_FIELD_NUMBER;
    hash = (53 * hash) + getPhase().hashCode();
    hash = (37 * hash) + READY_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getReady());
    hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
    hash = (53 * hash) + getPlayers();
    hash = (37 * hash) + SLOTS_FIELD_NUMBER;
    hash = (53 * hash) + getSlots();
    hash = (37 * hash) + TPS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTps()));
    hash = (37 * hash) + MSPT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getMspt()));
    hash = (37 * hash) + AGE_SECONDS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAgeSeconds());
    hash = (37 * hash) + RETIRING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getRetiring());
    hash = (37 * hash) + HELD_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getHeld());
    hash = (37 * hash) + DRAINING_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDraining());
    if (hasUsage()) {
      hash = (37 * hash) + USAGE_FIELD_NUMBER;
      hash = (53 * hash) + getUsage().hashCode();
    }
    hash = (37 * hash) + NODE_FIELD_NUMBER;
    hash = (53 * hash) + getNode().hashCode();
    hash = (37 * hash) + PLAYABLE_SLOTS_FIELD_NUMBER;
    hash = (53 * hash) + getPlayableSlots();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.InstanceStatus parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.InstanceStatus parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.InstanceStatus parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.InstanceStatus prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code spawnery.agent.v1alpha1.InstanceStatus}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.InstanceStatus)
      cloud.spawnery.agent.pb.InstanceStatusOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_InstanceStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_InstanceStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.InstanceStatus.class, cloud.spawnery.agent.pb.InstanceStatus.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.InstanceStatus.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetUsageFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      group_ = "";
      proxy_ = false;
      phase_ = "";
      ready_ = false;
      players_ = 0;
      slots_ = 0;
      tps_ = 0D;
      mspt_ = 0D;
      ageSeconds_ = 0L;
      retiring_ = false;
      held_ = false;
      draining_ = false;
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      node_ = "";
      playableSlots_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_InstanceStatus_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.InstanceStatus getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.InstanceStatus.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.InstanceStatus build() {
      cloud.spawnery.agent.pb.InstanceStatus result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.InstanceStatus buildPartial() {
      cloud.spawnery.agent.pb.InstanceStatus result = new cloud.spawnery.agent.pb.InstanceStatus(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.spawnery.agent.pb.InstanceStatus result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.group_ = group_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.proxy_ = proxy_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.phase_ = phase_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.ready_ = ready_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.players_ = players_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.slots_ = slots_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.tps_ = tps_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.mspt_ = mspt_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.ageSeconds_ = ageSeconds_;
      }
      if (((from_bitField0_ & 0x00000400) != 0)) {
        result.retiring_ = retiring_;
      }
      if (((from_bitField0_ & 0x00000800) != 0)) {
        result.held_ = held_;
      }
      if (((from_bitField0_ & 0x00001000) != 0)) {
        result.draining_ = draining_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00002000) != 0)) {
        result.usage_ = usageBuilder_ == null
            ? usage_
            : usageBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00004000) != 0)) {
        result.node_ = node_;
      }
      if (((from_bitField0_ & 0x00008000) != 0)) {
        result.playableSlots_ = playableSlots_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.InstanceStatus) {
        return mergeFrom((cloud.spawnery.agent.pb.InstanceStatus)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.InstanceStatus other) {
      if (other == cloud.spawnery.agent.pb.InstanceStatus.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getGroup().isEmpty()) {
        group_ = other.group_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getProxy() != false) {
        setProxy(other.getProxy());
      }
      if (!other.getPhase().isEmpty()) {
        phase_ = other.phase_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (other.getReady() != false) {
        setReady(other.getReady());
      }
      if (other.getPlayers() != 0) {
        setPlayers(other.getPlayers());
      }
      if (other.getSlots() != 0) {
        setSlots(other.getSlots());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getTps()) != 0) {
        setTps(other.getTps());
      }
      if (java.lang.Double.doubleToRawLongBits(other.getMspt()) != 0) {
        setMspt(other.getMspt());
      }
      if (other.getAgeSeconds() != 0L) {
        setAgeSeconds(other.getAgeSeconds());
      }
      if (other.getRetiring() != false) {
        setRetiring(other.getRetiring());
      }
      if (other.getHeld() != false) {
        setHeld(other.getHeld());
      }
      if (other.getDraining() != false) {
        setDraining(other.getDraining());
      }
      if (other.hasUsage()) {
        mergeUsage(other.getUsage());
      }
      if (!other.getNode().isEmpty()) {
        node_ = other.node_;
        bitField0_ |= 0x00004000;
        onChanged();
      }
      if (other.getPlayableSlots() != 0) {
        setPlayableSlots(other.getPlayableSlots());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              group_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 24: {
              proxy_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              phase_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              ready_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              players_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              slots_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 65: {
              tps_ = input.readDouble();
              bitField0_ |= 0x00000080;
              break;
            } // case 65
            case 73: {
              mspt_ = input.readDouble();
              bitField0_ |= 0x00000100;
              break;
            } // case 73
            case 80: {
              ageSeconds_ = input.readInt64();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            case 88: {
              retiring_ = input.readBool();
              bitField0_ |= 0x00000400;
              break;
            } // case 88
            case 96: {
              held_ = input.readBool();
              bitField0_ |= 0x00000800;
              break;
            } // case 96
            case 104: {
              draining_ = input.readBool();
              bitField0_ |= 0x00001000;
              break;
            } // case 104
            case 114: {
              input.readMessage(
                  internalGetUsageFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00002000;
              break;
            } // case 114
            case 122: {
              node_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00004000;
              break;
            } // case 122
            case 128: {
              playableSlots_ = input.readInt32();
              bitField0_ |= 0x00008000;
              break;
            } // case 128
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object group_ = "";
    /**
     * <code>string group = 2;</code>
     * @return The group.
     */
    public java.lang.String getGroup() {
      java.lang.Object ref = group_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        group_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string group = 2;</code>
     * @return The bytes for group.
     */
    public com.google.protobuf.ByteString
        getGroupBytes() {
      java.lang.Object ref = group_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        group_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string group = 2;</code>
     * @param value The group to set.
     * @return This builder for chaining.
     */
    public Builder setGroup(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      group_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string group = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearGroup() {
      group_ = getDefaultInstance().getGroup();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string group = 2;</code>
     * @param value The bytes for group to set.
     * @return This builder for chaining.
     */
    public Builder setGroupBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      group_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private boolean proxy_ ;
    /**
     * <code>bool proxy = 3;</code>
     * @return The proxy.
     */
    @java.lang.Override
    public boolean getProxy() {
      return proxy_;
    }
    /**
     * <code>bool proxy = 3;</code>
     * @param value The proxy to set.
     * @return This builder for chaining.
     */
    public Builder setProxy(boolean value) {

      proxy_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool proxy = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearProxy() {
      bitField0_ = (bitField0_ & ~0x00000004);
      proxy_ = false;
      onChanged();
      return this;
    }

    private java.lang.Object phase_ = "";
    /**
     * <pre>
     * A server's phase; empty for a proxy, whose state is ready and draining.
     * </pre>
     *
     * <code>string phase = 4;</code>
     * @return The phase.
     */
    public java.lang.String getPhase() {
      java.lang.Object ref = phase_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        phase_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * A server's phase; empty for a proxy, whose state is ready and draining.
     * </pre>
     *
     * <code>string phase = 4;</code>
     * @return The bytes for phase.
     */
    public com.google.protobuf.ByteString
        getPhaseBytes() {
      java.lang.Object ref = phase_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        phase_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * A server's phase; empty for a proxy, whose state is ready and draining.
     * </pre>
     *
     * <code>string phase = 4;</code>
     * @param value The phase to set.
     * @return This builder for chaining.
     */
    public Builder setPhase(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      phase_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A server's phase; empty for a proxy, whose state is ready and draining.
     * </pre>
     *
     * <code>string phase = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhase() {
      phase_ = getDefaultInstance().getPhase();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * A server's phase; empty for a proxy, whose state is ready and draining.
     * </pre>
     *
     * <code>string phase = 4;</code>
     * @param value The bytes for phase to set.
     * @return This builder for chaining.
     */
    public Builder setPhaseBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      phase_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private boolean ready_ ;
    /**
     * <code>bool ready = 5;</code>
     * @return The ready.
     */
    @java.lang.Override
    public boolean getReady() {
      return ready_;
    }
    /**
     * <code>bool ready = 5;</code>
     * @param value The ready to set.
     * @return This builder for chaining.
     */
    public Builder setReady(boolean value) {

      ready_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool ready = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearReady() {
      bitField0_ = (bitField0_ & ~0x00000010);
      ready_ = false;
      onChanged();
      return this;
    }

    private int players_ ;
    /**
     * <code>int32 players = 6;</code>
     * @return The players.
     */
    @java.lang.Override
    public int getPlayers() {
      return players_;
    }
    /**
     * <code>int32 players = 6;</code>
     * @param value The players to set.
     * @return This builder for chaining.
     */
    public Builder setPlayers(int value) {

      players_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 players = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayers() {
      bitField0_ = (bitField0_ & ~0x00000020);
      players_ = 0;
      onChanged();
      return this;
    }

    private int slots_ ;
    /**
     * <code>int32 slots = 7;</code>
     * @return The slots.
     */
    @java.lang.Override
    public int getSlots() {
      return slots_;
    }
    /**
     * <code>int32 slots = 7;</code>
     * @param value The slots to set.
     * @return This builder for chaining.
     */
    public Builder setSlots(int value) {

      slots_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 slots = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearSlots() {
      bitField0_ = (bitField0_ & ~0x00000040);
      slots_ = 0;
      onChanged();
      return this;
    }

    private double tps_ ;
    /**
     * <pre>
     * 0 = not reported
     * </pre>
     *
     * <code>double tps = 8;</code>
     * @return The tps.
     */
    @java.lang.Override
    public double getTps() {
      return tps_;
    }
    /**
     * <pre>
     * 0 = not reported
     * </pre>
     *
     * <code>double tps = 8;</code>
     * @param value The tps to set.
     * @return This builder for chaining.
     */
    public Builder setTps(double value) {

      tps_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0 = not reported
     * </pre>
     *
     * <code>double tps = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearTps() {
      bitField0_ = (bitField0_ & ~0x00000080);
      tps_ = 0D;
      onChanged();
      return this;
    }

    private double mspt_ ;
    /**
     * <pre>
     * 0 = not reported
     * </pre>
     *
     * <code>double mspt = 9;</code>
     * @return The mspt.
     */
    @java.lang.Override
    public double getMspt() {
      return mspt_;
    }
    /**
     * <pre>
     * 0 = not reported
     * </pre>
     *
     * <code>double mspt = 9;</code>
     * @param value The mspt to set.
     * @return This builder for chaining.
     */
    public Builder setMspt(double value) {

      mspt_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 0 = not reported
     * </pre>
     *
     * <code>double mspt = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearMspt() {
      bitField0_ = (bitField0_ & ~0x00000100);
      mspt_ = 0D;
      onChanged();
      return this;
    }

    private long ageSeconds_ ;
    /**
     * <code>int64 age_seconds = 10;</code>
     * @return The ageSeconds.
     */
    @java.lang.Override
    public long getAgeSeconds() {
      return ageSeconds_;
    }
    /**
     * <code>int64 age_seconds = 10;</code>
     * @param value The ageSeconds to set.
     * @return This builder for chaining.
     */
    public Builder setAgeSeconds(long value) {

      ageSeconds_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int64 age_seconds = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearAgeSeconds() {
      bitField0_ = (bitField0_ & ~0x00000200);
      ageSeconds_ = 0L;
      onChanged();
      return this;
    }

    private boolean retiring_ ;
    /**
     * <code>bool retiring = 11;</code>
     * @return The retiring.
     */
    @java.lang.Override
    public boolean getRetiring() {
      return retiring_;
    }
    /**
     * <code>bool retiring = 11;</code>
     * @param value The retiring to set.
     * @return This builder for chaining.
     */
    public Builder setRetiring(boolean value) {

      retiring_ = value;
      bitField0_ |= 0x00000400;
      onChanged();
      return this;
    }
    /**
     * <code>bool retiring = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearRetiring() {
      bitField0_ = (bitField0_ & ~0x00000400);
      retiring_ = false;
      onChanged();
      return this;
    }

    private boolean held_ ;
    /**
     * <code>bool held = 12;</code>
     * @return The held.
     */
    @java.lang.Override
    public boolean getHeld() {
      return held_;
    }
    /**
     * <code>bool held = 12;</code>
     * @param value The held to set.
     * @return This builder for chaining.
     */
    public Builder setHeld(boolean value) {

      held_ = value;
      bitField0_ |= 0x00000800;
      onChanged();
      return this;
    }
    /**
     * <code>bool held = 12;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeld() {
      bitField0_ = (bitField0_ & ~0x00000800);
      held_ = false;
      onChanged();
      return this;
    }

    private boolean draining_ ;
    /**
     * <code>bool draining = 13;</code>
     * @return The draining.
     */
    @java.lang.Override
    public boolean getDraining() {
      return draining_;
    }
    /**
     * <code>bool draining = 13;</code>
     * @param value The draining to set.
     * @return This builder for chaining.
     */
    public Builder setDraining(boolean value) {

      draining_ = value;
      bitField0_ |= 0x00001000;
      onChanged();
      return this;
    }
    /**
     * <code>bool draining = 13;</code>
     * @return This builder for chaining.
     */
    public Builder clearDraining() {
      bitField0_ = (bitField0_ & ~0x00001000);
      draining_ = false;
      onChanged();
      return this;
    }

    private cloud.spawnery.agent.pb.ResourceUsage usage_;
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder> usageBuilder_;
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     * @return Whether the usage field is set.
     */
    public boolean hasUsage() {
      return ((bitField0_ & 0x00002000) != 0);
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     * @return The usage.
     */
    public cloud.spawnery.agent.pb.ResourceUsage getUsage() {
      if (usageBuilder_ == null) {
        return usage_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : usage_;
      } else {
        return usageBuilder_.getMessage();
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     */
    public Builder setUsage(cloud.spawnery.agent.pb.ResourceUsage value) {
      if (usageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        usage_ = value;
      } else {
        usageBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     */
    public Builder setUsage(
        cloud.spawnery.agent.pb.ResourceUsage.Builder builderForValue) {
      if (usageBuilder_ == null) {
        usage_ = builderForValue.build();
      } else {
        usageBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00002000;
      onChanged();
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     */
    public Builder mergeUsage(cloud.spawnery.agent.pb.ResourceUsage value) {
      if (usageBuilder_ == null) {
        if (((bitField0_ & 0x00002000) != 0) &&
          usage_ != null &&
          usage_ != cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance()) {
          getUsageBuilder().mergeFrom(value);
        } else {
          usage_ = value;
        }
      } else {
        usageBuilder_.mergeFrom(value);
      }
      if (usage_ != null) {
        bitField0_ |= 0x00002000;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     */
    public Builder clearUsage() {
      bitField0_ = (bitField0_ & ~0x00002000);
      usage_ = null;
      if (usageBuilder_ != null) {
        usageBuilder_.dispose();
        usageBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     */
    public cloud.spawnery.agent.pb.ResourceUsage.Builder getUsageBuilder() {
      bitField0_ |= 0x00002000;
      onChanged();
      return internalGetUsageFieldBuilder().getBuilder();
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     */
    public cloud.spawnery.agent.pb.ResourceUsageOrBuilder getUsageOrBuilder() {
      if (usageBuilder_ != null) {
        return usageBuilder_.getMessageOrBuilder();
      } else {
        return usage_ == null ?
            cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : usage_;
      }
    }
    /**
     * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder> 
        internalGetUsageFieldBuilder() {
      if (usageBuilder_ == null) {
        usageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder>(
                getUsage(),
                getParentForChildren(),
                isClean());
        usage_ = null;
      }
      return usageBuilder_;
    }

    private java.lang.Object node_ = "";
    /**
     * <pre>
     * as ServerState.node
     * </pre>
     *
     * <code>string node = 15;</code>
     * @return The node.
     */
    public java.lang.String getNode() {
      java.lang.Object ref = node_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        node_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * as ServerState.node
     * </pre>
     *
     * <code>string node = 15;</code>
     * @return The bytes for node.
     */
    public com.google.protobuf.ByteString
        getNodeBytes() {
      java.lang.Object ref = node_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        node_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * as ServerState.node
     * </pre>
     *
     * <code>string node = 15;</code>
     * @param value The node to set.
     * @return This builder for chaining.
     */
    public Builder setNode(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      node_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * as ServerState.node
     * </pre>
     *
     * <code>string node = 15;</code>
     * @return This builder for chaining.
     */
    public Builder clearNode() {
      node_ = getDefaultInstance().getNode();
      bitField0_ = (bitField0_ & ~0x00004000);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * as ServerState.node
     * </pre>
     *
     * <code>string node = 15;</code>
     * @param value The bytes for node to set.
     * @return This builder for chaining.
     */
    public Builder setNodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      node_ = value;
      bitField0_ |= 0x00004000;
      onChanged();
      return this;
    }

    private int playableSlots_ ;
    /**
     * <pre>
     * as ServerState.playable_slots
     * </pre>
     *
     * <code>int32 playable_slots = 16;</code>
     * @return The playableSlots.
     */
    @java.lang.Override
    public int getPlayableSlots() {
      return playableSlots_;
    }
    /**
     * <pre>
     * as ServerState.playable_slots
     * </pre>
     *
     * <code>int32 playable_slots = 16;</code>
     * @param value The playableSlots to set.
     * @return This builder for chaining.
     */
    public Builder setPlayableSlots(int value) {

      playableSlots_ = value;
      bitField0_ |= 0x00008000;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * as ServerState.playable_slots
     * </pre>
     *
     * <code>int32 playable_slots = 16;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayableSlots() {
      bitField0_ = (bitField0_ & ~0x00008000);
      playableSlots_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.InstanceStatus)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.InstanceStatus)
  private static final cloud.spawnery.agent.pb.InstanceStatus DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.InstanceStatus();
  }

  public static cloud.spawnery.agent.pb.InstanceStatus getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<InstanceStatus>
      PARSER = new com.google.protobuf.AbstractParser<InstanceStatus>() {
    @java.lang.Override
    public InstanceStatus parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<InstanceStatus> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<InstanceStatus> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.InstanceStatus getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

