// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface InstanceStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.InstanceStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string group = 2;</code>
   * @return The group.
   */
  java.lang.String getGroup();
  /**
   * <code>string group = 2;</code>
   * @return The bytes for group.
   */
  com.google.protobuf.ByteString
      getGroupBytes();

  /**
   * <code>bool proxy = 3;</code>
   * @return The proxy.
   */
  boolean getProxy();

  /**
   * <pre>
   * A server's phase; empty for a proxy, whose state is ready and draining.
   * </pre>
   *
   * <code>string phase = 4;</code>
   * @return The phase.
   */
  java.lang.String getPhase();
  /**
   * <pre>
   * A server's phase; empty for a proxy, whose state is ready and draining.
   * </pre>
   *
   * <code>string phase = 4;</code>
   * @return The bytes for phase.
   */
  com.google.protobuf.ByteString
      getPhaseBytes();

  /**
   * <code>bool ready = 5;</code>
   * @return The ready.
   */
  boolean getReady();

  /**
   * <code>int32 players = 6;</code>
   * @return The players.
   */
  int getPlayers();

  /**
   * <code>int32 slots = 7;</code>
   * @return The slots.
   */
  int getSlots();

  /**
   * <pre>
   * 0 = not reported
   * </pre>
   *
   * <code>double tps = 8;</code>
   * @return The tps.
   */
  double getTps();

  /**
   * <pre>
   * 0 = not reported
   * </pre>
   *
   * <code>double mspt = 9;</code>
   * @return The mspt.
   */
  double getMspt();

  /**
   * <code>int64 age_seconds = 10;</code>
   * @return The ageSeconds.
   */
  long getAgeSeconds();

  /**
   * <code>bool retiring = 11;</code>
   * @return The retiring.
   */
  boolean getRetiring();

  /**
   * <code>bool held = 12;</code>
   * @return The held.
   */
  boolean getHeld();

  /**
   * <code>bool draining = 13;</code>
   * @return The draining.
   */
  boolean getDraining();

  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
   * @return Whether the usage field is set.
   */
  boolean hasUsage();
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
   * @return The usage.
   */
  cloud.spawnery.agent.pb.ResourceUsage getUsage();
  /**
   * <code>.spawnery.agent.v1alpha1.ResourceUsage usage = 14;</code>
   */
  cloud.spawnery.agent.pb.ResourceUsageOrBuilder getUsageOrBuilder();
}
