// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface PlayerCountOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.PlayerCount)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 players = 1;</code>
   * @return The players.
   */
  int getPlayers();

  /**
   * <code>int32 slots = 2;</code>
   * @return The slots.
   */
  int getSlots();

  /**
   * <pre>
   * Server agents only: the server's one-minute TPS average and its mean tick
   * duration in milliseconds. 0 means not reported -- what a proxy and an
   * agent older than these fields send.
   * </pre>
   *
   * <code>double tps = 3;</code>
   * @return The tps.
   */
  double getTps();

  /**
   * <code>double mspt = 4;</code>
   * @return The mspt.
   */
  double getMspt();
}
