// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface ResourceUsageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.ResourceUsage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 cpu_used_millicores = 1;</code>
   * @return The cpuUsedMillicores.
   */
  long getCpuUsedMillicores();

  /**
   * <code>int64 cpu_requested_millicores = 2;</code>
   * @return The cpuRequestedMillicores.
   */
  long getCpuRequestedMillicores();

  /**
   * <code>int64 cpu_limit_millicores = 3;</code>
   * @return The cpuLimitMillicores.
   */
  long getCpuLimitMillicores();

  /**
   * <pre>
   * Some container has no CPU limit, so cpu_limit_millicores is a floor.
   * </pre>
   *
   * <code>bool cpu_unlimited = 4;</code>
   * @return The cpuUnlimited.
   */
  boolean getCpuUnlimited();

  /**
   * <code>int64 memory_used_bytes = 5;</code>
   * @return The memoryUsedBytes.
   */
  long getMemoryUsedBytes();

  /**
   * <code>int64 memory_requested_bytes = 6;</code>
   * @return The memoryRequestedBytes.
   */
  long getMemoryRequestedBytes();

  /**
   * <code>int64 memory_limit_bytes = 7;</code>
   * @return The memoryLimitBytes.
   */
  long getMemoryLimitBytes();

  /**
   * <code>bool memory_unlimited = 8;</code>
   * @return The memoryUnlimited.
   */
  boolean getMemoryUnlimited();

  /**
   * <code>int32 pods = 9;</code>
   * @return The pods.
   */
  int getPods();

  /**
   * <pre>
   * Pods with a metrics sample; the used figures cover these only.
   * </pre>
   *
   * <code>int32 pods_measured = 10;</code>
   * @return The podsMeasured.
   */
  int getPodsMeasured();
}
