// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * <pre>
 * ResourceUsage is a set of pods: what they use, and what they asked for.
 * </pre>
 *
 * Protobuf type {@code spawnery.agent.v1alpha1.ResourceUsage}
 */
@com.google.protobuf.Generated
public final class ResourceUsage extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.ResourceUsage)
    ResourceUsageOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ResourceUsage");
  }
  // Use ResourceUsage.newBuilder() to construct.
  private ResourceUsage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ResourceUsage() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ResourceUsage_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ResourceUsage_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ResourceUsage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.ResourceUsage.class, cloud.spawnery.agent.pb.ResourceUsage.Builder.class);
  }

  public static final int CPU_USED_MILLICORES_FIELD_NUMBER = 1;
  private long cpuUsedMillicores_ = 0L;
  /**
   * <code>int64 cpu_used_millicores = 1;</code>
   * @return The cpuUsedMillicores.
   */
  @java.lang.Override
  public long getCpuUsedMillicores() {
    return cpuUsedMillicores_;
  }

  public static final int CPU_REQUESTED_MILLICORES_FIELD_NUMBER = 2;
  private long cpuRequestedMillicores_ = 0L;
  /**
   * <code>int64 cpu_requested_millicores = 2;</code>
   * @return The cpuRequestedMillicores.
   */
  @java.lang.Override
  public long getCpuRequestedMillicores() {
    return cpuRequestedMillicores_;
  }

  public static final int CPU_LIMIT_MILLICORES_FIELD_NUMBER = 3;
  private long cpuLimitMillicores_ = 0L;
  /**
   * <code>int64 cpu_limit_millicores = 3;</code>
   * @return The cpuLimitMillicores.
   */
  @java.lang.Override
  public long getCpuLimitMillicores() {
    return cpuLimitMillicores_;
  }

  public static final int CPU_UNLIMITED_FIELD_NUMBER = 4;
  private boolean cpuUnlimited_ = false;
  /**
   * <pre>
   * Some container has no CPU limit, so cpu_limit_millicores is a floor.
   * </pre>
   *
   * <code>bool cpu_unlimited = 4;</code>
   * @return The cpuUnlimited.
   */
  @java.lang.Override
  public boolean getCpuUnlimited() {
    return cpuUnlimited_;
  }

  public static final int MEMORY_USED_BYTES_FIELD_NUMBER = 5;
  private long memoryUsedBytes_ = 0L;
  /**
   * <code>int64 memory_used_bytes = 5;</code>
   * @return The memoryUsedBytes.
   */
  @java.lang.Override
  public long getMemoryUsedBytes() {
    return memoryUsedBytes_;
  }

  public static final int MEMORY_REQUESTED_BYTES_FIELD_NUMBER = 6;
  private long memoryRequestedBytes_ = 0L;
  /**
   * <code>int64 memory_requested_bytes = 6;</code>
   * @return The memoryRequestedBytes.
   */
  @java.lang.Override
  public long getMemoryRequestedBytes() {
    return memoryRequestedBytes_;
  }

  public static final int MEMORY_LIMIT_BYTES_FIELD_NUMBER = 7;
  private long memoryLimitBytes_ = 0L;
  /**
   * <code>int64 memory_limit_bytes = 7;</code>
   * @return The memoryLimitBytes.
   */
  @java.lang.Override
  public long getMemoryLimitBytes() {
    return memoryLimitBytes_;
  }

  public static final int MEMORY_UNLIMITED_FIELD_NUMBER = 8;
  private boolean memoryUnlimited_ = false;
  /**
   * <code>bool memory_unlimited = 8;</code>
   * @return The memoryUnlimited.
   */
  @java.lang.Override
  public boolean getMemoryUnlimited() {
    return memoryUnlimited_;
  }

  public static final int PODS_FIELD_NUMBER = 9;
  private int pods_ = 0;
  /**
   * <code>int32 pods = 9;</code>
   * @return The pods.
   */
  @java.lang.Override
  public int getPods() {
    return pods_;
  }

  public static final int PODS_MEASURED_FIELD_NUMBER = 10;
  private int podsMeasured_ = 0;
  /**
   * <pre>
   * Pods with a metrics sample; the used figures cover these only.
   * </pre>
   *
   * <code>int32 pods_measured = 10;</code>
   * @return The podsMeasured.
   */
  @java.lang.Override
  public int getPodsMeasured() {
    return podsMeasured_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (cpuUsedMillicores_ != 0L) {
      output.writeInt64(1, cpuUsedMillicores_);
    }
    if (cpuRequestedMillicores_ != 0L) {
      output.writeInt64(2, cpuRequestedMillicores_);
    }
    if (cpuLimitMillicores_ != 0L) {
      output.writeInt64(3, cpuLimitMillicores_);
    }
    if (cpuUnlimited_ != false) {
      output.writeBool(4, cpuUnlimited_);
    }
    if (memoryUsedBytes_ != 0L) {
      output.writeInt64(5, memoryUsedBytes_);
    }
    if (memoryRequestedBytes_ != 0L) {
      output.writeInt64(6, memoryRequestedBytes_);
    }
    if (memoryLimitBytes_ != 0L) {
      output.writeInt64(7, memoryLimitBytes_);
    }
    if (memoryUnlimited_ != false) {
      output.writeBool(8, memoryUnlimited_);
    }
    if (pods_ != 0) {
      output.writeInt32(9, pods_);
    }
    if (podsMeasured_ != 0) {
      output.writeInt32(10, podsMeasured_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (cpuUsedMillicores_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, cpuUsedMillicores_);
    }
    if (cpuRequestedMillicores_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, cpuRequestedMillicores_);
    }
    if (cpuLimitMillicores_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, cpuLimitMillicores_);
    }
    if (cpuUnlimited_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(4, cpuUnlimited_);
    }
    if (memoryUsedBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, memoryUsedBytes_);
    }
    if (memoryRequestedBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, memoryRequestedBytes_);
    }
    if (memoryLimitBytes_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, memoryLimitBytes_);
    }
    if (memoryUnlimited_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, memoryUnlimited_);
    }
    if (pods_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(9, pods_);
    }
    if (podsMeasured_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, podsMeasured_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.ResourceUsage)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.ResourceUsage other = (cloud.spawnery.agent.pb.ResourceUsage) obj;

    if (getCpuUsedMillicores()
        != other.getCpuUsedMillicores()) return false;
    if (getCpuRequestedMillicores()
        != other.getCpuRequestedMillicores()) return false;
    if (getCpuLimitMillicores()
        != other.getCpuLimitMillicores()) return false;
    if (getCpuUnlimited()
        != other.getCpuUnlimited()) return false;
    if (getMemoryUsedBytes()
        != other.getMemoryUsedBytes()) return false;
    if (getMemoryRequestedBytes()
        != other.getMemoryRequestedBytes()) return false;
    if (getMemoryLimitBytes()
        != other.getMemoryLimitBytes()) return false;
    if (getMemoryUnlimited()
        != other.getMemoryUnlimited()) return false;
    if (getPods()
        != other.getPods()) return false;
    if (getPodsMeasured()
        != other.getPodsMeasured()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CPU_USED_MILLICORES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCpuUsedMillicores());
    hash = (37 * hash) + CPU_REQUESTED_MILLICORES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCpuRequestedMillicores());
    hash = (37 * hash) + CPU_LIMIT_MILLICORES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCpuLimitMillicores());
    hash = (37 * hash) + CPU_UNLIMITED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getCpuUnlimited());
    hash = (37 * hash) + MEMORY_USED_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemoryUsedBytes());
    hash = (37 * hash) + MEMORY_REQUESTED_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemoryRequestedBytes());
    hash = (37 * hash) + MEMORY_LIMIT_BYTES_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getMemoryLimitBytes());
    hash = (37 * hash) + MEMORY_UNLIMITED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMemoryUnlimited());
    hash = (37 * hash) + PODS_FIELD_NUMBER;
    hash = (53 * hash) + getPods();
    hash = (37 * hash) + PODS_MEASURED_FIELD_NUMBER;
    hash = (53 * hash) + getPodsMeasured();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.ResourceUsage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.ResourceUsage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.ResourceUsage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.ResourceUsage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * ResourceUsage is a set of pods: what they use, and what they asked for.
   * </pre>
   *
   * Protobuf type {@code spawnery.agent.v1alpha1.ResourceUsage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.ResourceUsage)
      cloud.spawnery.agent.pb.ResourceUsageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ResourceUsage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ResourceUsage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.ResourceUsage.class, cloud.spawnery.agent.pb.ResourceUsage.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.ResourceUsage.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      cpuUsedMillicores_ = 0L;
      cpuRequestedMillicores_ = 0L;
      cpuLimitMillicores_ = 0L;
      cpuUnlimited_ = false;
      memoryUsedBytes_ = 0L;
      memoryRequestedBytes_ = 0L;
      memoryLimitBytes_ = 0L;
      memoryUnlimited_ = false;
      pods_ = 0;
      podsMeasured_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_ResourceUsage_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ResourceUsage getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ResourceUsage build() {
      cloud.spawnery.agent.pb.ResourceUsage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.ResourceUsage buildPartial() {
      cloud.spawnery.agent.pb.ResourceUsage result = new cloud.spawnery.agent.pb.ResourceUsage(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(cloud.spawnery.agent.pb.ResourceUsage result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.cpuUsedMillicores_ = cpuUsedMillicores_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.cpuRequestedMillicores_ = cpuRequestedMillicores_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.cpuLimitMillicores_ = cpuLimitMillicores_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.cpuUnlimited_ = cpuUnlimited_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.memoryUsedBytes_ = memoryUsedBytes_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.memoryRequestedBytes_ = memoryRequestedBytes_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.memoryLimitBytes_ = memoryLimitBytes_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.memoryUnlimited_ = memoryUnlimited_;
      }
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.pods_ = pods_;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.podsMeasured_ = podsMeasured_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.ResourceUsage) {
        return mergeFrom((cloud.spawnery.agent.pb.ResourceUsage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.ResourceUsage other) {
      if (other == cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance()) return this;
      if (other.getCpuUsedMillicores() != 0L) {
        setCpuUsedMillicores(other.getCpuUsedMillicores());
      }
      if (other.getCpuRequestedMillicores() != 0L) {
        setCpuRequestedMillicores(other.getCpuRequestedMillicores());
      }
      if (other.getCpuLimitMillicores() != 0L) {
        setCpuLimitMillicores(other.getCpuLimitMillicores());
      }
      if (other.getCpuUnlimited() != false) {
        setCpuUnlimited(other.getCpuUnlimited());
      }
      if (other.getMemoryUsedBytes() != 0L) {
        setMemoryUsedBytes(other.getMemoryUsedBytes());
      }
      if (other.getMemoryRequestedBytes() != 0L) {
        setMemoryRequestedBytes(other.getMemoryRequestedBytes());
      }
      if (other.getMemoryLimitBytes() != 0L) {
        setMemoryLimitBytes(other.getMemoryLimitBytes());
      }
      if (other.getMemoryUnlimited() != false) {
        setMemoryUnlimited(other.getMemoryUnlimited());
      }
      if (other.getPods() != 0) {
        setPods(other.getPods());
      }
      if (other.getPodsMeasured() != 0) {
        setPodsMeasured(other.getPodsMeasured());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              cpuUsedMillicores_ = input.readInt64();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              cpuRequestedMillicores_ = input.readInt64();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              cpuLimitMillicores_ = input.readInt64();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              cpuUnlimited_ = input.readBool();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              memoryUsedBytes_ = input.readInt64();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              memoryRequestedBytes_ = input.readInt64();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              memoryLimitBytes_ = input.readInt64();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              memoryUnlimited_ = input.readBool();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            case 72: {
              pods_ = input.readInt32();
              bitField0_ |= 0x00000100;
              break;
            } // case 72
            case 80: {
              podsMeasured_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private long cpuUsedMillicores_ ;
    /**
     * <code>int64 cpu_used_millicores = 1;</code>
     * @return The cpuUsedMillicores.
     */
    @java.lang.Override
    public long getCpuUsedMillicores() {
      return cpuUsedMillicores_;
    }
    /**
     * <code>int64 cpu_used_millicores = 1;</code>
     * @param value The cpuUsedMillicores to set.
     * @return This builder for chaining.
     */
    public Builder setCpuUsedMillicores(long value) {

      cpuUsedMillicores_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cpu_used_millicores = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuUsedMillicores() {
      bitField0_ = (bitField0_ & ~0x00000001);
      cpuUsedMillicores_ = 0L;
      onChanged();
      return this;
    }

    private long cpuRequestedMillicores_ ;
    /**
     * <code>int64 cpu_requested_millicores = 2;</code>
     * @return The cpuRequestedMillicores.
     */
    @java.lang.Override
    public long getCpuRequestedMillicores() {
      return cpuRequestedMillicores_;
    }
    /**
     * <code>int64 cpu_requested_millicores = 2;</code>
     * @param value The cpuRequestedMillicores to set.
     * @return This builder for chaining.
     */
    public Builder setCpuRequestedMillicores(long value) {

      cpuRequestedMillicores_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cpu_requested_millicores = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuRequestedMillicores() {
      bitField0_ = (bitField0_ & ~0x00000002);
      cpuRequestedMillicores_ = 0L;
      onChanged();
      return this;
    }

    private long cpuLimitMillicores_ ;
    /**
     * <code>int64 cpu_limit_millicores = 3;</code>
     * @return The cpuLimitMillicores.
     */
    @java.lang.Override
    public long getCpuLimitMillicores() {
      return cpuLimitMillicores_;
    }
    /**
     * <code>int64 cpu_limit_millicores = 3;</code>
     * @param value The cpuLimitMillicores to set.
     * @return This builder for chaining.
     */
    public Builder setCpuLimitMillicores(long value) {

      cpuLimitMillicores_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>int64 cpu_limit_millicores = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuLimitMillicores() {
      bitField0_ = (bitField0_ & ~0x00000004);
      cpuLimitMillicores_ = 0L;
      onChanged();
      return this;
    }

    private boolean cpuUnlimited_ ;
    /**
     * <pre>
     * Some container has no CPU limit, so cpu_limit_millicores is a floor.
     * </pre>
     *
     * <code>bool cpu_unlimited = 4;</code>
     * @return The cpuUnlimited.
     */
    @java.lang.Override
    public boolean getCpuUnlimited() {
      return cpuUnlimited_;
    }
    /**
     * <pre>
     * Some container has no CPU limit, so cpu_limit_millicores is a floor.
     * </pre>
     *
     * <code>bool cpu_unlimited = 4;</code>
     * @param value The cpuUnlimited to set.
     * @return This builder for chaining.
     */
    public Builder setCpuUnlimited(boolean value) {

      cpuUnlimited_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Some container has no CPU limit, so cpu_limit_millicores is a floor.
     * </pre>
     *
     * <code>bool cpu_unlimited = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearCpuUnlimited() {
      bitField0_ = (bitField0_ & ~0x00000008);
      cpuUnlimited_ = false;
      onChanged();
      return this;
    }

    private long memoryUsedBytes_ ;
    /**
     * <code>int64 memory_used_bytes = 5;</code>
     * @return The memoryUsedBytes.
     */
    @java.lang.Override
    public long getMemoryUsedBytes() {
      return memoryUsedBytes_;
    }
    /**
     * <code>int64 memory_used_bytes = 5;</code>
     * @param value The memoryUsedBytes to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryUsedBytes(long value) {

      memoryUsedBytes_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>int64 memory_used_bytes = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryUsedBytes() {
      bitField0_ = (bitField0_ & ~0x00000010);
      memoryUsedBytes_ = 0L;
      onChanged();
      return this;
    }

    private long memoryRequestedBytes_ ;
    /**
     * <code>int64 memory_requested_bytes = 6;</code>
     * @return The memoryRequestedBytes.
     */
    @java.lang.Override
    public long getMemoryRequestedBytes() {
      return memoryRequestedBytes_;
    }
    /**
     * <code>int64 memory_requested_bytes = 6;</code>
     * @param value The memoryRequestedBytes to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryRequestedBytes(long value) {

      memoryRequestedBytes_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int64 memory_requested_bytes = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryRequestedBytes() {
      bitField0_ = (bitField0_ & ~0x00000020);
      memoryRequestedBytes_ = 0L;
      onChanged();
      return this;
    }

    private long memoryLimitBytes_ ;
    /**
     * <code>int64 memory_limit_bytes = 7;</code>
     * @return The memoryLimitBytes.
     */
    @java.lang.Override
    public long getMemoryLimitBytes() {
      return memoryLimitBytes_;
    }
    /**
     * <code>int64 memory_limit_bytes = 7;</code>
     * @param value The memoryLimitBytes to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryLimitBytes(long value) {

      memoryLimitBytes_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int64 memory_limit_bytes = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryLimitBytes() {
      bitField0_ = (bitField0_ & ~0x00000040);
      memoryLimitBytes_ = 0L;
      onChanged();
      return this;
    }

    private boolean memoryUnlimited_ ;
    /**
     * <code>bool memory_unlimited = 8;</code>
     * @return The memoryUnlimited.
     */
    @java.lang.Override
    public boolean getMemoryUnlimited() {
      return memoryUnlimited_;
    }
    /**
     * <code>bool memory_unlimited = 8;</code>
     * @param value The memoryUnlimited to set.
     * @return This builder for chaining.
     */
    public Builder setMemoryUnlimited(boolean value) {

      memoryUnlimited_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>bool memory_unlimited = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearMemoryUnlimited() {
      bitField0_ = (bitField0_ & ~0x00000080);
      memoryUnlimited_ = false;
      onChanged();
      return this;
    }

    private int pods_ ;
    /**
     * <code>int32 pods = 9;</code>
     * @return The pods.
     */
    @java.lang.Override
    public int getPods() {
      return pods_;
    }
    /**
     * <code>int32 pods = 9;</code>
     * @param value The pods to set.
     * @return This builder for chaining.
     */
    public Builder setPods(int value) {

      pods_ = value;
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>int32 pods = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearPods() {
      bitField0_ = (bitField0_ & ~0x00000100);
      pods_ = 0;
      onChanged();
      return this;
    }

    private int podsMeasured_ ;
    /**
     * <pre>
     * Pods with a metrics sample; the used figures cover these only.
     * </pre>
     *
     * <code>int32 pods_measured = 10;</code>
     * @return The podsMeasured.
     */
    @java.lang.Override
    public int getPodsMeasured() {
      return podsMeasured_;
    }
    /**
     * <pre>
     * Pods with a metrics sample; the used figures cover these only.
     * </pre>
     *
     * <code>int32 pods_measured = 10;</code>
     * @param value The podsMeasured to set.
     * @return This builder for chaining.
     */
    public Builder setPodsMeasured(int value) {

      podsMeasured_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pods with a metrics sample; the used figures cover these only.
     * </pre>
     *
     * <code>int32 pods_measured = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearPodsMeasured() {
      bitField0_ = (bitField0_ & ~0x00000200);
      podsMeasured_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.ResourceUsage)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.ResourceUsage)
  private static final cloud.spawnery.agent.pb.ResourceUsage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.ResourceUsage();
  }

  public static cloud.spawnery.agent.pb.ResourceUsage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ResourceUsage>
      PARSER = new com.google.protobuf.AbstractParser<ResourceUsage>() {
    @java.lang.Override
    public ResourceUsage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ResourceUsage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ResourceUsage> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

