// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface StatusResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.StatusResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The whole network, the target group, or the target instance.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
   * @return Whether the total field is set.
   */
  boolean hasTotal();
  /**
   * <pre>
   * The whole network, the target group, or the target instance.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
   * @return The total.
   */
  cloud.spawnery.agent.pb.ResourceUsage getTotal();
  /**
   * <pre>
   * The whole network, the target group, or the target instance.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
   */
  cloud.spawnery.agent.pb.ResourceUsageOrBuilder getTotalOrBuilder();

  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  java.util.List<cloud.spawnery.agent.pb.GroupStatus> 
      getGroupsList();
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  cloud.spawnery.agent.pb.GroupStatus getGroups(int index);
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  int getGroupsCount();
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  java.util.List<? extends cloud.spawnery.agent.pb.GroupStatusOrBuilder> 
      getGroupsOrBuilderList();
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  cloud.spawnery.agent.pb.GroupStatusOrBuilder getGroupsOrBuilder(
      int index);

  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  java.util.List<cloud.spawnery.agent.pb.InstanceStatus> 
      getInstancesList();
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  cloud.spawnery.agent.pb.InstanceStatus getInstances(int index);
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  int getInstancesCount();
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  java.util.List<? extends cloud.spawnery.agent.pb.InstanceStatusOrBuilder> 
      getInstancesOrBuilderList();
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  cloud.spawnery.agent.pb.InstanceStatusOrBuilder getInstancesOrBuilder(
      int index);

  /**
   * <pre>
   * Pods of the namespace outside every listed group. Network form only.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
   * @return Whether the other field is set.
   */
  boolean hasOther();
  /**
   * <pre>
   * Pods of the namespace outside every listed group. Network form only.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
   * @return The other.
   */
  cloud.spawnery.agent.pb.ResourceUsage getOther();
  /**
   * <pre>
   * Pods of the namespace outside every listed group. Network form only.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
   */
  cloud.spawnery.agent.pb.ResourceUsageOrBuilder getOtherOrBuilder();

  /**
   * <code>bool metrics_available = 5;</code>
   * @return The metricsAvailable.
   */
  boolean getMetricsAvailable();

  /**
   * <code>int32 players = 6;</code>
   * @return The players.
   */
  int getPlayers();

  /**
   * <code>int32 servers = 7;</code>
   * @return The servers.
   */
  int getServers();

  /**
   * <code>int32 proxies = 8;</code>
   * @return The proxies.
   */
  int getProxies();
}
