// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

@com.google.protobuf.Generated
public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:spawnery.agent.v1alpha1.StatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Empty for the whole network, else a server group, a proxy group, a
   * server or a proxy, looked up in that order.
   * </pre>
   *
   * <code>string target = 1;</code>
   * @return The target.
   */
  java.lang.String getTarget();
  /**
   * <pre>
   * Empty for the whole network, else a server group, a proxy group, a
   * server or a proxy, looked up in that order.
   * </pre>
   *
   * <code>string target = 1;</code>
   * @return The bytes for target.
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
