// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: spawnery/agent/v1alpha1/agent.proto
// Protobuf Java Version: 4.35.1

package cloud.spawnery.agent.pb;

/**
 * Protobuf type {@code spawnery.agent.v1alpha1.StatusResult}
 */
@com.google.protobuf.Generated
public final class StatusResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:spawnery.agent.v1alpha1.StatusResult)
    StatusResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "StatusResult");
  }
  // Use StatusResult.newBuilder() to construct.
  private StatusResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private StatusResult() {
    groups_ = java.util.Collections.emptyList();
    instances_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_StatusResult_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_StatusResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_StatusResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            cloud.spawnery.agent.pb.StatusResult.class, cloud.spawnery.agent.pb.StatusResult.Builder.class);
  }

  private int bitField0_;
  public static final int TOTAL_FIELD_NUMBER = 1;
  private cloud.spawnery.agent.pb.ResourceUsage total_;
  /**
   * <pre>
   * The whole network, the target group, or the target instance.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
   * @return Whether the total field is set.
   */
  @java.lang.Override
  public boolean hasTotal() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <pre>
   * The whole network, the target group, or the target instance.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
   * @return The total.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsage getTotal() {
    return total_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : total_;
  }
  /**
   * <pre>
   * The whole network, the target group, or the target instance.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsageOrBuilder getTotalOrBuilder() {
    return total_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : total_;
  }

  public static final int GROUPS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private java.util.List<cloud.spawnery.agent.pb.GroupStatus> groups_;
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.spawnery.agent.pb.GroupStatus> getGroupsList() {
    return groups_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.spawnery.agent.pb.GroupStatusOrBuilder> 
      getGroupsOrBuilderList() {
    return groups_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  @java.lang.Override
  public int getGroupsCount() {
    return groups_.size();
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.GroupStatus getGroups(int index) {
    return groups_.get(index);
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.GroupStatusOrBuilder getGroupsOrBuilder(
      int index) {
    return groups_.get(index);
  }

  public static final int INSTANCES_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<cloud.spawnery.agent.pb.InstanceStatus> instances_;
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  @java.lang.Override
  public java.util.List<cloud.spawnery.agent.pb.InstanceStatus> getInstancesList() {
    return instances_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends cloud.spawnery.agent.pb.InstanceStatusOrBuilder> 
      getInstancesOrBuilderList() {
    return instances_;
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  @java.lang.Override
  public int getInstancesCount() {
    return instances_.size();
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.InstanceStatus getInstances(int index) {
    return instances_.get(index);
  }
  /**
   * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.InstanceStatusOrBuilder getInstancesOrBuilder(
      int index) {
    return instances_.get(index);
  }

  public static final int OTHER_FIELD_NUMBER = 4;
  private cloud.spawnery.agent.pb.ResourceUsage other_;
  /**
   * <pre>
   * Pods of the namespace outside every listed group. Network form only.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
   * @return Whether the other field is set.
   */
  @java.lang.Override
  public boolean hasOther() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <pre>
   * Pods of the namespace outside every listed group. Network form only.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
   * @return The other.
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsage getOther() {
    return other_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : other_;
  }
  /**
   * <pre>
   * Pods of the namespace outside every listed group. Network form only.
   * </pre>
   *
   * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
   */
  @java.lang.Override
  public cloud.spawnery.agent.pb.ResourceUsageOrBuilder getOtherOrBuilder() {
    return other_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : other_;
  }

  public static final int METRICS_AVAILABLE_FIELD_NUMBER = 5;
  private boolean metricsAvailable_ = false;
  /**
   * <code>bool metrics_available = 5;</code>
   * @return The metricsAvailable.
   */
  @java.lang.Override
  public boolean getMetricsAvailable() {
    return metricsAvailable_;
  }

  public static final int PLAYERS_FIELD_NUMBER = 6;
  private int players_ = 0;
  /**
   * <code>int32 players = 6;</code>
   * @return The players.
   */
  @java.lang.Override
  public int getPlayers() {
    return players_;
  }

  public static final int SERVERS_FIELD_NUMBER = 7;
  private int servers_ = 0;
  /**
   * <code>int32 servers = 7;</code>
   * @return The servers.
   */
  @java.lang.Override
  public int getServers() {
    return servers_;
  }

  public static final int PROXIES_FIELD_NUMBER = 8;
  private int proxies_ = 0;
  /**
   * <code>int32 proxies = 8;</code>
   * @return The proxies.
   */
  @java.lang.Override
  public int getProxies() {
    return proxies_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getTotal());
    }
    for (int i = 0; i < groups_.size(); i++) {
      output.writeMessage(2, groups_.get(i));
    }
    for (int i = 0; i < instances_.size(); i++) {
      output.writeMessage(3, instances_.get(i));
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeMessage(4, getOther());
    }
    if (metricsAvailable_ != false) {
      output.writeBool(5, metricsAvailable_);
    }
    if (players_ != 0) {
      output.writeInt32(6, players_);
    }
    if (servers_ != 0) {
      output.writeInt32(7, servers_);
    }
    if (proxies_ != 0) {
      output.writeInt32(8, proxies_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTotal());
    }

        {
          final int count = groups_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(groups_.get(i));
          }
          size += 1 * count;
        }

        {
          final int count = instances_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(instances_.get(i));
          }
          size += 1 * count;
        }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOther());
    }
    if (metricsAvailable_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, metricsAvailable_);
    }
    if (players_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, players_);
    }
    if (servers_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, servers_);
    }
    if (proxies_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, proxies_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof cloud.spawnery.agent.pb.StatusResult)) {
      return super.equals(obj);
    }
    cloud.spawnery.agent.pb.StatusResult other = (cloud.spawnery.agent.pb.StatusResult) obj;

    if (hasTotal() != other.hasTotal()) return false;
    if (hasTotal()) {
      if (!getTotal()
          .equals(other.getTotal())) return false;
    }
    if (!getGroupsList()
        .equals(other.getGroupsList())) return false;
    if (!getInstancesList()
        .equals(other.getInstancesList())) return false;
    if (hasOther() != other.hasOther()) return false;
    if (hasOther()) {
      if (!getOther()
          .equals(other.getOther())) return false;
    }
    if (getMetricsAvailable()
        != other.getMetricsAvailable()) return false;
    if (getPlayers()
        != other.getPlayers()) return false;
    if (getServers()
        != other.getServers()) return false;
    if (getProxies()
        != other.getProxies()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTotal()) {
      hash = (37 * hash) + TOTAL_FIELD_NUMBER;
      hash = (53 * hash) + getTotal().hashCode();
    }
    if (getGroupsCount() > 0) {
      hash = (37 * hash) + GROUPS_FIELD_NUMBER;
      hash = (53 * hash) + getGroupsList().hashCode();
    }
    if (getInstancesCount() > 0) {
      hash = (37 * hash) + INSTANCES_FIELD_NUMBER;
      hash = (53 * hash) + getInstancesList().hashCode();
    }
    if (hasOther()) {
      hash = (37 * hash) + OTHER_FIELD_NUMBER;
      hash = (53 * hash) + getOther().hashCode();
    }
    hash = (37 * hash) + METRICS_AVAILABLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getMetricsAvailable());
    hash = (37 * hash) + PLAYERS_FIELD_NUMBER;
    hash = (53 * hash) + getPlayers();
    hash = (37 * hash) + SERVERS_FIELD_NUMBER;
    hash = (53 * hash) + getServers();
    hash = (37 * hash) + PROXIES_FIELD_NUMBER;
    hash = (53 * hash) + getProxies();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static cloud.spawnery.agent.pb.StatusResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static cloud.spawnery.agent.pb.StatusResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static cloud.spawnery.agent.pb.StatusResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static cloud.spawnery.agent.pb.StatusResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(cloud.spawnery.agent.pb.StatusResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code spawnery.agent.v1alpha1.StatusResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:spawnery.agent.v1alpha1.StatusResult)
      cloud.spawnery.agent.pb.StatusResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_StatusResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_StatusResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cloud.spawnery.agent.pb.StatusResult.class, cloud.spawnery.agent.pb.StatusResult.Builder.class);
    }

    // Construct using cloud.spawnery.agent.pb.StatusResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTotalFieldBuilder();
        internalGetGroupsFieldBuilder();
        internalGetInstancesFieldBuilder();
        internalGetOtherFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      total_ = null;
      if (totalBuilder_ != null) {
        totalBuilder_.dispose();
        totalBuilder_ = null;
      }
      if (groupsBuilder_ == null) {
        groups_ = java.util.Collections.emptyList();
      } else {
        groups_ = null;
        groupsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000002);
      if (instancesBuilder_ == null) {
        instances_ = java.util.Collections.emptyList();
      } else {
        instances_ = null;
        instancesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      other_ = null;
      if (otherBuilder_ != null) {
        otherBuilder_.dispose();
        otherBuilder_ = null;
      }
      metricsAvailable_ = false;
      players_ = 0;
      servers_ = 0;
      proxies_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return cloud.spawnery.agent.pb.AgentProto.internal_static_spawnery_agent_v1alpha1_StatusResult_descriptor;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.StatusResult getDefaultInstanceForType() {
      return cloud.spawnery.agent.pb.StatusResult.getDefaultInstance();
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.StatusResult build() {
      cloud.spawnery.agent.pb.StatusResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public cloud.spawnery.agent.pb.StatusResult buildPartial() {
      cloud.spawnery.agent.pb.StatusResult result = new cloud.spawnery.agent.pb.StatusResult(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(cloud.spawnery.agent.pb.StatusResult result) {
      if (groupsBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0)) {
          groups_ = java.util.Collections.unmodifiableList(groups_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.groups_ = groups_;
      } else {
        result.groups_ = groupsBuilder_.build();
      }
      if (instancesBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          instances_ = java.util.Collections.unmodifiableList(instances_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.instances_ = instances_;
      } else {
        result.instances_ = instancesBuilder_.build();
      }
    }

    private void buildPartial0(cloud.spawnery.agent.pb.StatusResult result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.total_ = totalBuilder_ == null
            ? total_
            : totalBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.other_ = otherBuilder_ == null
            ? other_
            : otherBuilder_.build();
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.metricsAvailable_ = metricsAvailable_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.players_ = players_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        result.servers_ = servers_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.proxies_ = proxies_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof cloud.spawnery.agent.pb.StatusResult) {
        return mergeFrom((cloud.spawnery.agent.pb.StatusResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(cloud.spawnery.agent.pb.StatusResult other) {
      if (other == cloud.spawnery.agent.pb.StatusResult.getDefaultInstance()) return this;
      if (other.hasTotal()) {
        mergeTotal(other.getTotal());
      }
      if (groupsBuilder_ == null) {
        if (!other.groups_.isEmpty()) {
          if (groups_.isEmpty()) {
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureGroupsIsMutable();
            groups_.addAll(other.groups_);
          }
          onChanged();
        }
      } else {
        if (!other.groups_.isEmpty()) {
          if (groupsBuilder_.isEmpty()) {
            groupsBuilder_.dispose();
            groupsBuilder_ = null;
            groups_ = other.groups_;
            bitField0_ = (bitField0_ & ~0x00000002);
            groupsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetGroupsFieldBuilder() : null;
          } else {
            groupsBuilder_.addAllMessages(other.groups_);
          }
        }
      }
      if (instancesBuilder_ == null) {
        if (!other.instances_.isEmpty()) {
          if (instances_.isEmpty()) {
            instances_ = other.instances_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureInstancesIsMutable();
            instances_.addAll(other.instances_);
          }
          onChanged();
        }
      } else {
        if (!other.instances_.isEmpty()) {
          if (instancesBuilder_.isEmpty()) {
            instancesBuilder_.dispose();
            instancesBuilder_ = null;
            instances_ = other.instances_;
            bitField0_ = (bitField0_ & ~0x00000004);
            instancesBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetInstancesFieldBuilder() : null;
          } else {
            instancesBuilder_.addAllMessages(other.instances_);
          }
        }
      }
      if (other.hasOther()) {
        mergeOther(other.getOther());
      }
      if (other.getMetricsAvailable() != false) {
        setMetricsAvailable(other.getMetricsAvailable());
      }
      if (other.getPlayers() != 0) {
        setPlayers(other.getPlayers());
      }
      if (other.getServers() != 0) {
        setServers(other.getServers());
      }
      if (other.getProxies() != 0) {
        setProxies(other.getProxies());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetTotalFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              cloud.spawnery.agent.pb.GroupStatus m =
                  input.readMessage(
                      cloud.spawnery.agent.pb.GroupStatus.parser(),
                      extensionRegistry);
              if (groupsBuilder_ == null) {
                ensureGroupsIsMutable();
                groups_.add(m);
              } else {
                groupsBuilder_.addMessage(m);
              }
              break;
            } // case 18
            case 26: {
              cloud.spawnery.agent.pb.InstanceStatus m =
                  input.readMessage(
                      cloud.spawnery.agent.pb.InstanceStatus.parser(),
                      extensionRegistry);
              if (instancesBuilder_ == null) {
                ensureInstancesIsMutable();
                instances_.add(m);
              } else {
                instancesBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  internalGetOtherFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 40: {
              metricsAvailable_ = input.readBool();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              players_ = input.readInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            case 56: {
              servers_ = input.readInt32();
              bitField0_ |= 0x00000040;
              break;
            } // case 56
            case 64: {
              proxies_ = input.readInt32();
              bitField0_ |= 0x00000080;
              break;
            } // case 64
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private cloud.spawnery.agent.pb.ResourceUsage total_;
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder> totalBuilder_;
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     * @return Whether the total field is set.
     */
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     * @return The total.
     */
    public cloud.spawnery.agent.pb.ResourceUsage getTotal() {
      if (totalBuilder_ == null) {
        return total_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : total_;
      } else {
        return totalBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     */
    public Builder setTotal(cloud.spawnery.agent.pb.ResourceUsage value) {
      if (totalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        total_ = value;
      } else {
        totalBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     */
    public Builder setTotal(
        cloud.spawnery.agent.pb.ResourceUsage.Builder builderForValue) {
      if (totalBuilder_ == null) {
        total_ = builderForValue.build();
      } else {
        totalBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     */
    public Builder mergeTotal(cloud.spawnery.agent.pb.ResourceUsage value) {
      if (totalBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          total_ != null &&
          total_ != cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance()) {
          getTotalBuilder().mergeFrom(value);
        } else {
          total_ = value;
        }
      } else {
        totalBuilder_.mergeFrom(value);
      }
      if (total_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     */
    public Builder clearTotal() {
      bitField0_ = (bitField0_ & ~0x00000001);
      total_ = null;
      if (totalBuilder_ != null) {
        totalBuilder_.dispose();
        totalBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     */
    public cloud.spawnery.agent.pb.ResourceUsage.Builder getTotalBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetTotalFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     */
    public cloud.spawnery.agent.pb.ResourceUsageOrBuilder getTotalOrBuilder() {
      if (totalBuilder_ != null) {
        return totalBuilder_.getMessageOrBuilder();
      } else {
        return total_ == null ?
            cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : total_;
      }
    }
    /**
     * <pre>
     * The whole network, the target group, or the target instance.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage total = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder> 
        internalGetTotalFieldBuilder() {
      if (totalBuilder_ == null) {
        totalBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder>(
                getTotal(),
                getParentForChildren(),
                isClean());
        total_ = null;
      }
      return totalBuilder_;
    }

    private java.util.List<cloud.spawnery.agent.pb.GroupStatus> groups_ =
      java.util.Collections.emptyList();
    private void ensureGroupsIsMutable() {
      if (!((bitField0_ & 0x00000002) != 0)) {
        groups_ = new java.util.ArrayList<cloud.spawnery.agent.pb.GroupStatus>(groups_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.GroupStatus, cloud.spawnery.agent.pb.GroupStatus.Builder, cloud.spawnery.agent.pb.GroupStatusOrBuilder> groupsBuilder_;

    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.GroupStatus> getGroupsList() {
      if (groupsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(groups_);
      } else {
        return groupsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public int getGroupsCount() {
      if (groupsBuilder_ == null) {
        return groups_.size();
      } else {
        return groupsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public cloud.spawnery.agent.pb.GroupStatus getGroups(int index) {
      if (groupsBuilder_ == null) {
        return groups_.get(index);
      } else {
        return groupsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder setGroups(
        int index, cloud.spawnery.agent.pb.GroupStatus value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.set(index, value);
        onChanged();
      } else {
        groupsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder setGroups(
        int index, cloud.spawnery.agent.pb.GroupStatus.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.set(index, builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder addGroups(cloud.spawnery.agent.pb.GroupStatus value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.add(value);
        onChanged();
      } else {
        groupsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder addGroups(
        int index, cloud.spawnery.agent.pb.GroupStatus value) {
      if (groupsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureGroupsIsMutable();
        groups_.add(index, value);
        onChanged();
      } else {
        groupsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder addGroups(
        cloud.spawnery.agent.pb.GroupStatus.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.add(builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder addGroups(
        int index, cloud.spawnery.agent.pb.GroupStatus.Builder builderForValue) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.add(index, builderForValue.build());
        onChanged();
      } else {
        groupsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder addAllGroups(
        java.lang.Iterable<? extends cloud.spawnery.agent.pb.GroupStatus> values) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, groups_);
        onChanged();
      } else {
        groupsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder clearGroups() {
      if (groupsBuilder_ == null) {
        groups_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        groupsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public Builder removeGroups(int index) {
      if (groupsBuilder_ == null) {
        ensureGroupsIsMutable();
        groups_.remove(index);
        onChanged();
      } else {
        groupsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public cloud.spawnery.agent.pb.GroupStatus.Builder getGroupsBuilder(
        int index) {
      return internalGetGroupsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public cloud.spawnery.agent.pb.GroupStatusOrBuilder getGroupsOrBuilder(
        int index) {
      if (groupsBuilder_ == null) {
        return groups_.get(index);  } else {
        return groupsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public java.util.List<? extends cloud.spawnery.agent.pb.GroupStatusOrBuilder> 
         getGroupsOrBuilderList() {
      if (groupsBuilder_ != null) {
        return groupsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(groups_);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public cloud.spawnery.agent.pb.GroupStatus.Builder addGroupsBuilder() {
      return internalGetGroupsFieldBuilder().addBuilder(
          cloud.spawnery.agent.pb.GroupStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public cloud.spawnery.agent.pb.GroupStatus.Builder addGroupsBuilder(
        int index) {
      return internalGetGroupsFieldBuilder().addBuilder(
          index, cloud.spawnery.agent.pb.GroupStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.GroupStatus groups = 2;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.GroupStatus.Builder> 
         getGroupsBuilderList() {
      return internalGetGroupsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.GroupStatus, cloud.spawnery.agent.pb.GroupStatus.Builder, cloud.spawnery.agent.pb.GroupStatusOrBuilder> 
        internalGetGroupsFieldBuilder() {
      if (groupsBuilder_ == null) {
        groupsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.spawnery.agent.pb.GroupStatus, cloud.spawnery.agent.pb.GroupStatus.Builder, cloud.spawnery.agent.pb.GroupStatusOrBuilder>(
                groups_,
                ((bitField0_ & 0x00000002) != 0),
                getParentForChildren(),
                isClean());
        groups_ = null;
      }
      return groupsBuilder_;
    }

    private java.util.List<cloud.spawnery.agent.pb.InstanceStatus> instances_ =
      java.util.Collections.emptyList();
    private void ensureInstancesIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        instances_ = new java.util.ArrayList<cloud.spawnery.agent.pb.InstanceStatus>(instances_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.InstanceStatus, cloud.spawnery.agent.pb.InstanceStatus.Builder, cloud.spawnery.agent.pb.InstanceStatusOrBuilder> instancesBuilder_;

    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.InstanceStatus> getInstancesList() {
      if (instancesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(instances_);
      } else {
        return instancesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public int getInstancesCount() {
      if (instancesBuilder_ == null) {
        return instances_.size();
      } else {
        return instancesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public cloud.spawnery.agent.pb.InstanceStatus getInstances(int index) {
      if (instancesBuilder_ == null) {
        return instances_.get(index);
      } else {
        return instancesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder setInstances(
        int index, cloud.spawnery.agent.pb.InstanceStatus value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.set(index, value);
        onChanged();
      } else {
        instancesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder setInstances(
        int index, cloud.spawnery.agent.pb.InstanceStatus.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.set(index, builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder addInstances(cloud.spawnery.agent.pb.InstanceStatus value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.add(value);
        onChanged();
      } else {
        instancesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder addInstances(
        int index, cloud.spawnery.agent.pb.InstanceStatus value) {
      if (instancesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureInstancesIsMutable();
        instances_.add(index, value);
        onChanged();
      } else {
        instancesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder addInstances(
        cloud.spawnery.agent.pb.InstanceStatus.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.add(builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder addInstances(
        int index, cloud.spawnery.agent.pb.InstanceStatus.Builder builderForValue) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.add(index, builderForValue.build());
        onChanged();
      } else {
        instancesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder addAllInstances(
        java.lang.Iterable<? extends cloud.spawnery.agent.pb.InstanceStatus> values) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, instances_);
        onChanged();
      } else {
        instancesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder clearInstances() {
      if (instancesBuilder_ == null) {
        instances_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        instancesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public Builder removeInstances(int index) {
      if (instancesBuilder_ == null) {
        ensureInstancesIsMutable();
        instances_.remove(index);
        onChanged();
      } else {
        instancesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public cloud.spawnery.agent.pb.InstanceStatus.Builder getInstancesBuilder(
        int index) {
      return internalGetInstancesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public cloud.spawnery.agent.pb.InstanceStatusOrBuilder getInstancesOrBuilder(
        int index) {
      if (instancesBuilder_ == null) {
        return instances_.get(index);  } else {
        return instancesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public java.util.List<? extends cloud.spawnery.agent.pb.InstanceStatusOrBuilder> 
         getInstancesOrBuilderList() {
      if (instancesBuilder_ != null) {
        return instancesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(instances_);
      }
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public cloud.spawnery.agent.pb.InstanceStatus.Builder addInstancesBuilder() {
      return internalGetInstancesFieldBuilder().addBuilder(
          cloud.spawnery.agent.pb.InstanceStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public cloud.spawnery.agent.pb.InstanceStatus.Builder addInstancesBuilder(
        int index) {
      return internalGetInstancesFieldBuilder().addBuilder(
          index, cloud.spawnery.agent.pb.InstanceStatus.getDefaultInstance());
    }
    /**
     * <code>repeated .spawnery.agent.v1alpha1.InstanceStatus instances = 3;</code>
     */
    public java.util.List<cloud.spawnery.agent.pb.InstanceStatus.Builder> 
         getInstancesBuilderList() {
      return internalGetInstancesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        cloud.spawnery.agent.pb.InstanceStatus, cloud.spawnery.agent.pb.InstanceStatus.Builder, cloud.spawnery.agent.pb.InstanceStatusOrBuilder> 
        internalGetInstancesFieldBuilder() {
      if (instancesBuilder_ == null) {
        instancesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            cloud.spawnery.agent.pb.InstanceStatus, cloud.spawnery.agent.pb.InstanceStatus.Builder, cloud.spawnery.agent.pb.InstanceStatusOrBuilder>(
                instances_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        instances_ = null;
      }
      return instancesBuilder_;
    }

    private cloud.spawnery.agent.pb.ResourceUsage other_;
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder> otherBuilder_;
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     * @return Whether the other field is set.
     */
    public boolean hasOther() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     * @return The other.
     */
    public cloud.spawnery.agent.pb.ResourceUsage getOther() {
      if (otherBuilder_ == null) {
        return other_ == null ? cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : other_;
      } else {
        return otherBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     */
    public Builder setOther(cloud.spawnery.agent.pb.ResourceUsage value) {
      if (otherBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        other_ = value;
      } else {
        otherBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     */
    public Builder setOther(
        cloud.spawnery.agent.pb.ResourceUsage.Builder builderForValue) {
      if (otherBuilder_ == null) {
        other_ = builderForValue.build();
      } else {
        otherBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     */
    public Builder mergeOther(cloud.spawnery.agent.pb.ResourceUsage value) {
      if (otherBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          other_ != null &&
          other_ != cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance()) {
          getOtherBuilder().mergeFrom(value);
        } else {
          other_ = value;
        }
      } else {
        otherBuilder_.mergeFrom(value);
      }
      if (other_ != null) {
        bitField0_ |= 0x00000008;
        onChanged();
      }
      return this;
    }
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     */
    public Builder clearOther() {
      bitField0_ = (bitField0_ & ~0x00000008);
      other_ = null;
      if (otherBuilder_ != null) {
        otherBuilder_.dispose();
        otherBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     */
    public cloud.spawnery.agent.pb.ResourceUsage.Builder getOtherBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return internalGetOtherFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     */
    public cloud.spawnery.agent.pb.ResourceUsageOrBuilder getOtherOrBuilder() {
      if (otherBuilder_ != null) {
        return otherBuilder_.getMessageOrBuilder();
      } else {
        return other_ == null ?
            cloud.spawnery.agent.pb.ResourceUsage.getDefaultInstance() : other_;
      }
    }
    /**
     * <pre>
     * Pods of the namespace outside every listed group. Network form only.
     * </pre>
     *
     * <code>.spawnery.agent.v1alpha1.ResourceUsage other = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder> 
        internalGetOtherFieldBuilder() {
      if (otherBuilder_ == null) {
        otherBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            cloud.spawnery.agent.pb.ResourceUsage, cloud.spawnery.agent.pb.ResourceUsage.Builder, cloud.spawnery.agent.pb.ResourceUsageOrBuilder>(
                getOther(),
                getParentForChildren(),
                isClean());
        other_ = null;
      }
      return otherBuilder_;
    }

    private boolean metricsAvailable_ ;
    /**
     * <code>bool metrics_available = 5;</code>
     * @return The metricsAvailable.
     */
    @java.lang.Override
    public boolean getMetricsAvailable() {
      return metricsAvailable_;
    }
    /**
     * <code>bool metrics_available = 5;</code>
     * @param value The metricsAvailable to set.
     * @return This builder for chaining.
     */
    public Builder setMetricsAvailable(boolean value) {

      metricsAvailable_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>bool metrics_available = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMetricsAvailable() {
      bitField0_ = (bitField0_ & ~0x00000010);
      metricsAvailable_ = false;
      onChanged();
      return this;
    }

    private int players_ ;
    /**
     * <code>int32 players = 6;</code>
     * @return The players.
     */
    @java.lang.Override
    public int getPlayers() {
      return players_;
    }
    /**
     * <code>int32 players = 6;</code>
     * @param value The players to set.
     * @return This builder for chaining.
     */
    public Builder setPlayers(int value) {

      players_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>int32 players = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlayers() {
      bitField0_ = (bitField0_ & ~0x00000020);
      players_ = 0;
      onChanged();
      return this;
    }

    private int servers_ ;
    /**
     * <code>int32 servers = 7;</code>
     * @return The servers.
     */
    @java.lang.Override
    public int getServers() {
      return servers_;
    }
    /**
     * <code>int32 servers = 7;</code>
     * @param value The servers to set.
     * @return This builder for chaining.
     */
    public Builder setServers(int value) {

      servers_ = value;
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <code>int32 servers = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearServers() {
      bitField0_ = (bitField0_ & ~0x00000040);
      servers_ = 0;
      onChanged();
      return this;
    }

    private int proxies_ ;
    /**
     * <code>int32 proxies = 8;</code>
     * @return The proxies.
     */
    @java.lang.Override
    public int getProxies() {
      return proxies_;
    }
    /**
     * <code>int32 proxies = 8;</code>
     * @param value The proxies to set.
     * @return This builder for chaining.
     */
    public Builder setProxies(int value) {

      proxies_ = value;
      bitField0_ |= 0x00000080;
      onChanged();
      return this;
    }
    /**
     * <code>int32 proxies = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearProxies() {
      bitField0_ = (bitField0_ & ~0x00000080);
      proxies_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:spawnery.agent.v1alpha1.StatusResult)
  }

  // @@protoc_insertion_point(class_scope:spawnery.agent.v1alpha1.StatusResult)
  private static final cloud.spawnery.agent.pb.StatusResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new cloud.spawnery.agent.pb.StatusResult();
  }

  public static cloud.spawnery.agent.pb.StatusResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<StatusResult>
      PARSER = new com.google.protobuf.AbstractParser<StatusResult>() {
    @java.lang.Override
    public StatusResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<StatusResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<StatusResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public cloud.spawnery.agent.pb.StatusResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

